package farm.entity;
// Generated Nov 17, 2014 1:31:23 PM by Hibernate Tools 3.6.0


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * DtConstants generated by hbm2java
 */
@Entity
@Table(name="dt_constants"
    ,catalog="db_dms"
)
public class DtConstants  implements java.io.Serializable {


     private Integer id;
     private double rate;
     private double saleRate;
     private double shareRate;
     private double maxLimitLoan;
     private double maxLimitCredit;
     private String date;

    public DtConstants() {
    }

    public DtConstants(double rate, double saleRate, double shareRate,double maxLimitLoan, double maxLimitCredit, String date) {
       this.rate = rate;
       this.saleRate = saleRate;
       this.shareRate = shareRate;
       this.maxLimitLoan = maxLimitLoan;
       this.maxLimitCredit = maxLimitCredit;
       this.date = date;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="id", nullable=false)
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }

    
    @Column(name="rate", nullable=false, precision=2, scale=0)
    public double getRate() {
        return this.rate;
    }
    
    public void setRate(double rate) {
        this.rate = rate;
    }

    
    @Column(name="sale_rate", nullable=false, precision=2, scale=0)
    public double getSaleRate() {
        return this.saleRate;
    }
    
    public void setSaleRate(double saleRate) {
        this.saleRate = saleRate;
    }
    @Column(name="share_rate", nullable=false, precision=2, scale=0)
    public double getShareRate() {
        return shareRate;
    }

    public void setShareRate(double shareRate) {
        this.shareRate = shareRate;
    }

    
    @Column(name="max_limit_loan", nullable=false, precision=22, scale=0)
    public double getMaxLimitLoan() {
        return this.maxLimitLoan;
    }
    
    public void setMaxLimitLoan(double maxLimitLoan) {
        this.maxLimitLoan = maxLimitLoan;
    }

    
    @Column(name="max_limit_credit", nullable=false, precision=22, scale=0)
    public double getMaxLimitCredit() {
        return this.maxLimitCredit;
    }
    
    public void setMaxLimitCredit(double maxLimitCredit) {
        this.maxLimitCredit = maxLimitCredit;
    }

    
    @Column(name="date", nullable=false, length=20)
    public String getDate() {
        return this.date;
    }
    
    public void setDate(String date) {
        this.date = date;
    }




}


