package farm.entity;
// Generated Nov 17, 2014 1:31:23 PM by Hibernate Tools 3.6.0


import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * DtCRate generated by hbm2java
 */
@Entity
@Table(name="dt_c_rate"
    ,catalog="db_dms"
)
public class DtCRate  implements java.io.Serializable {


     private Integer id;
     private double CRate;
     private String type;
     private String code;
     private Date date;

    public DtCRate() {
    }

    public DtCRate(double CRate, String type, String code, Date date) {
       this.CRate = CRate;
       this.type = type;
       this.code = code;
       this.date = date;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="id", unique=true, nullable=false)
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }

    
    @Column(name="c_rate", nullable=false, precision=10)
    public double getCRate() {
        return this.CRate;
    }
    
    public void setCRate(double CRate) {
        this.CRate = CRate;
    }

    
    @Column(name="type", nullable=false, length=50)
    public String getType() {
        return this.type;
    }
    
    public void setType(String type) {
        this.type = type;
    }

    
    @Column(name="code", nullable=false, length=12)
    public String getCode() {
        return this.code;
    }
    
    public void setCode(String code) {
        this.code = code;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="date", nullable=false, length=10)
    public Date getDate() {
        return this.date;
    }
    
    public void setDate(Date date) {
        this.date = date;
    }




}


