package farm.entity;
// Generated Nov 17, 2014 1:31:23 PM by Hibernate Tools 3.6.0


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * DtFactory generated by hbm2java
 */
@Entity
@Table(name="dt_factory"
    ,catalog="db_dms"
)
public class DtFactory  implements java.io.Serializable {


     private Integer id;
     private String companyName;
     private String fname;
     private String lname;
     private String contact;
     private String phone;
     private String fax;
     private String aphone;
     private String acontact;
     private String email;
     private String cc;
     private String billTo;
     private String terms;
     private String comments;
     private String sendmethod;
     private double rate;

    public DtFactory() {
    }

    public DtFactory(String companyName, String fname, String lname, String contact, String phone, String fax, String aphone, String acontact, String email, String cc, String billTo, String terms, String comments, String sendmethod, double rate) {
       this.companyName = companyName;
       this.fname = fname;
       this.lname = lname;
       this.contact = contact;
       this.phone = phone;
       this.fax = fax;
       this.aphone = aphone;
       this.acontact = acontact;
       this.email = email;
       this.cc = cc;
       this.billTo = billTo;
       this.terms = terms;
       this.comments = comments;
       this.sendmethod = sendmethod;
       this.rate = rate;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="id", nullable=false)
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }

    
    @Column(name="CompanyName", nullable=false, length=100)
    public String getCompanyName() {
        return this.companyName;
    }
    
    public void setCompanyName(String companyName) {
        this.companyName = companyName;
    }

    
    @Column(name="Fname", nullable=false, length=50)
    public String getFname() {
        return this.fname;
    }
    
    public void setFname(String fname) {
        this.fname = fname;
    }

    
    @Column(name="Lname", nullable=false, length=50)
    public String getLname() {
        return this.lname;
    }
    
    public void setLname(String lname) {
        this.lname = lname;
    }

    
    @Column(name="Contact", nullable=false, length=50)
    public String getContact() {
        return this.contact;
    }
    
    public void setContact(String contact) {
        this.contact = contact;
    }

    
    @Column(name="Phone", nullable=false, length=50)
    public String getPhone() {
        return this.phone;
    }
    
    public void setPhone(String phone) {
        this.phone = phone;
    }

    
    @Column(name="Fax", nullable=false, length=50)
    public String getFax() {
        return this.fax;
    }
    
    public void setFax(String fax) {
        this.fax = fax;
    }

    
    @Column(name="APhone", nullable=false, length=50)
    public String getAphone() {
        return this.aphone;
    }
    
    public void setAphone(String aphone) {
        this.aphone = aphone;
    }

    
    @Column(name="AContact", nullable=false, length=50)
    public String getAcontact() {
        return this.acontact;
    }
    
    public void setAcontact(String acontact) {
        this.acontact = acontact;
    }

    
    @Column(name="Email", nullable=false, length=50)
    public String getEmail() {
        return this.email;
    }
    
    public void setEmail(String email) {
        this.email = email;
    }

    
    @Column(name="Cc", nullable=false, length=50)
    public String getCc() {
        return this.cc;
    }
    
    public void setCc(String cc) {
        this.cc = cc;
    }

    
    @Column(name="Bill_to", nullable=false, length=400)
    public String getBillTo() {
        return this.billTo;
    }
    
    public void setBillTo(String billTo) {
        this.billTo = billTo;
    }

    
    @Column(name="Terms", nullable=false, length=2000)
    public String getTerms() {
        return this.terms;
    }
    
    public void setTerms(String terms) {
        this.terms = terms;
    }

    
    @Column(name="Comments", nullable=false, length=2000)
    public String getComments() {
        return this.comments;
    }
    
    public void setComments(String comments) {
        this.comments = comments;
    }

    
    @Column(name="Sendmethod", nullable=false, length=2000)
    public String getSendmethod() {
        return this.sendmethod;
    }
    
    public void setSendmethod(String sendmethod) {
        this.sendmethod = sendmethod;
    }

    
    @Column(name="rate", nullable=false, precision=22, scale=0)
    public double getRate() {
        return this.rate;
    }
    
    public void setRate(double rate) {
        this.rate = rate;
    }




}


