/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package ui;

import ca.odell.glazedlists.GlazedLists;
import ca.odell.glazedlists.swing.AutoCompleteSupport;
import classes.rowcount;
import classes.superCls;
import custom_jPanels.RoundRectGradientPanel;
import custom_jPanels.SimpleGradientPanel;
import farm.entity.DtFactory;
import farmTech.util.HibernateUtil;
import java.util.Date;
import java.util.Iterator;
import java.util.List;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import org.hibernate.HibernateException;
import org.hibernate.Query;
import org.hibernate.Session;
import org.hibernate.Transaction;

/**
 *
 * @author Kent
 */
public class Factory_reg extends javax.swing.JInternalFrame {

    /**
     * Creates new form Factory_reg
     */
    superCls sup=new superCls();
    DtFactory comp;
    private AutoCompleteSupport company=null;
    private JLabel errorFields;
    private Object[] id;
    private String userid;
    public Factory_reg() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel4 = new SimpleGradientPanel();
        jLabel27 = new javax.swing.JLabel();
        cmbCustname = new javax.swing.JComboBox();
        jLabel28 = new javax.swing.JLabel();
        txtbalance = new javax.swing.JTextField();
        jLabel29 = new javax.swing.JLabel();
        jDateChooser3 = new com.toedter.calendar.JDateChooser();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel6 = new RoundRectGradientPanel();
        jLabel30 = new javax.swing.JLabel();
        jLabel33 = new javax.swing.JLabel();
        jLabel34 = new javax.swing.JLabel();
        txtCname = new javax.swing.JTextField();
        txtfname = new javax.swing.JTextField();
        txtlname = new javax.swing.JTextField();
        jLabel36 = new javax.swing.JLabel();
        jLabel37 = new javax.swing.JLabel();
        jLabel39 = new javax.swing.JLabel();
        jLabel40 = new javax.swing.JLabel();
        jLabel41 = new javax.swing.JLabel();
        jLabel42 = new javax.swing.JLabel();
        jLabel43 = new javax.swing.JLabel();
        txtcontact = new javax.swing.JTextField();
        txtCphone = new javax.swing.JTextField();
        txtCfax = new javax.swing.JTextField();
        txtaltphone = new javax.swing.JTextField();
        txtaltcontact = new javax.swing.JTextField();
        txtCemail = new javax.swing.JTextField();
        txtCcc = new javax.swing.JTextField();
        jLabel46 = new javax.swing.JLabel();
        jLabel51 = new javax.swing.JLabel();
        jLabel52 = new javax.swing.JLabel();
        jLabel59 = new javax.swing.JLabel();
        txtcustcode = new javax.swing.JTextField();
        jLabel84 = new javax.swing.JLabel();
        jLabel35 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        txtABill = new javax.swing.JTextArea();
        jButton7 = new javax.swing.JButton();
        jButton9 = new javax.swing.JButton();
        jButton8 = new javax.swing.JButton();
        jLabel58 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        txtRate = new javax.swing.JTextField();
        jPanel7 = new RoundRectGradientPanel();
        ;
        jLabel32 = new javax.swing.JLabel();
        jScrollPane4 = new javax.swing.JScrollPane();
        txtterms = new javax.swing.JTextArea();
        jLabel44 = new javax.swing.JLabel();
        jScrollPane5 = new javax.swing.JScrollPane();
        txtcomment = new javax.swing.JTextArea();
        jLabel45 = new javax.swing.JLabel();
        cmbmail = new javax.swing.JComboBox();
        jButton10 = new javax.swing.JButton();
        jButton11 = new javax.swing.JButton();
        jButton12 = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JSeparator();

        setClosable(true);
        setDefaultCloseOperation(javax.swing.WindowConstants.HIDE_ON_CLOSE);
        setIconifiable(true);
        setTitle("Customer Factory");
        setToolTipText("");
        setFrameIcon(new javax.swing.ImageIcon(getClass().getResource("/images/ox-cow.png"))); // NOI18N

        jPanel4.setName("card2"); // NOI18N

        jLabel27.setFont(new java.awt.Font("Trebuchet MS", 0, 11)); // NOI18N
        jLabel27.setText("Customer Name :");

        cmbCustname.setFont(new java.awt.Font("Trebuchet MS", 0, 11)); // NOI18N
        cmbCustname.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cmbCustnameItemStateChanged(evt);
            }
        });
        cmbCustname.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                cmbCustnameKeyReleased(evt);
            }
        });

        jLabel28.setFont(new java.awt.Font("Trebuchet MS", 0, 11)); // NOI18N
        jLabel28.setText("Balance :");

        txtbalance.setFont(new java.awt.Font("Trebuchet MS", 0, 11)); // NOI18N

        jLabel29.setFont(new java.awt.Font("Trebuchet MS", 0, 11)); // NOI18N
        jLabel29.setText("as of :");

        jDateChooser3.setDate(new Date());
        jDateChooser3.setDateFormatString("dd-MM-yyyy");
        jDateChooser3.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                jDateChooser3PropertyChange(evt);
            }
        });

        jLabel30.setFont(new java.awt.Font("Trebuchet MS", 0, 11)); // NOI18N
        jLabel30.setText("Company Name :");

        jLabel33.setFont(new java.awt.Font("Trebuchet MS", 0, 11)); // NOI18N
        jLabel33.setText("First Name : ");

        jLabel34.setFont(new java.awt.Font("Trebuchet MS", 0, 11)); // NOI18N
        jLabel34.setText("Last Name :");

        txtCname.setFont(new java.awt.Font("Trebuchet MS", 0, 11)); // NOI18N

        txtfname.setFont(new java.awt.Font("Trebuchet MS", 0, 11)); // NOI18N

        txtlname.setFont(new java.awt.Font("Trebuchet MS", 0, 11)); // NOI18N

        jLabel36.setFont(new java.awt.Font("Trebuchet MS", 0, 11)); // NOI18N
        jLabel36.setText("Contact :");

        jLabel37.setFont(new java.awt.Font("Trebuchet MS", 0, 11)); // NOI18N
        jLabel37.setText("Phone :");

        jLabel39.setFont(new java.awt.Font("Trebuchet MS", 0, 11)); // NOI18N
        jLabel39.setText("Fax :");

        jLabel40.setFont(new java.awt.Font("Trebuchet MS", 0, 11)); // NOI18N
        jLabel40.setText("Alt. Phone :");

        jLabel41.setFont(new java.awt.Font("Trebuchet MS", 0, 11)); // NOI18N
        jLabel41.setText("Alt.Contact :");

        jLabel42.setFont(new java.awt.Font("Trebuchet MS", 0, 11)); // NOI18N
        jLabel42.setText("Email :");

        jLabel43.setFont(new java.awt.Font("Trebuchet MS", 0, 11)); // NOI18N
        jLabel43.setText("Cc :");

        txtcontact.setFont(new java.awt.Font("Trebuchet MS", 0, 11)); // NOI18N

        txtCphone.setFont(new java.awt.Font("Trebuchet MS", 0, 11)); // NOI18N

        txtCfax.setFont(new java.awt.Font("Trebuchet MS", 0, 11)); // NOI18N

        txtaltphone.setFont(new java.awt.Font("Trebuchet MS", 0, 11)); // NOI18N

        txtaltcontact.setFont(new java.awt.Font("Trebuchet MS", 0, 11)); // NOI18N

        txtCemail.setFont(new java.awt.Font("Trebuchet MS", 0, 11)); // NOI18N

        txtCcc.setFont(new java.awt.Font("Trebuchet MS", 0, 11)); // NOI18N

        jLabel46.setForeground(new java.awt.Color(255, 51, 51));
        jLabel46.setText("*");

        jLabel51.setForeground(new java.awt.Color(255, 51, 51));
        jLabel51.setText("*");

        jLabel52.setForeground(new java.awt.Color(255, 51, 51));
        jLabel52.setText("*");

        jLabel59.setFont(new java.awt.Font("Trebuchet MS", 0, 11)); // NOI18N
        jLabel59.setText("CustomerCode :");

        txtcustcode.setFont(new java.awt.Font("Trebuchet MS", 0, 11)); // NOI18N

        jLabel84.setForeground(new java.awt.Color(255, 51, 51));
        jLabel84.setText("*");

        jLabel35.setFont(new java.awt.Font("Trebuchet MS", 0, 11)); // NOI18N
        jLabel35.setText("Invoice To:");

        txtABill.setColumns(20);
        txtABill.setFont(new java.awt.Font("Trebuchet MS", 0, 11)); // NOI18N
        txtABill.setRows(5);
        jScrollPane3.setViewportView(txtABill);

        jButton7.setFont(new java.awt.Font("Trebuchet MS", 0, 11)); // NOI18N
        jButton7.setText("Add New");
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });

        jButton9.setFont(new java.awt.Font("Trebuchet MS", 0, 11)); // NOI18N
        jButton9.setText("Delete");
        jButton9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton9ActionPerformed(evt);
            }
        });

        jButton8.setFont(new java.awt.Font("Trebuchet MS", 0, 11)); // NOI18N
        jButton8.setText("Edit");
        jButton8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton8ActionPerformed(evt);
            }
        });

        jLabel58.setFont(new java.awt.Font("Segoe UI", 0, 10)); // NOI18N
        jLabel58.setForeground(new java.awt.Color(255, 51, 51));
        jLabel58.setText("*  required fields");

        jLabel1.setFont(new java.awt.Font("Trebuchet MS", 0, 11)); // NOI18N
        jLabel1.setText("Rate :");

        txtRate.setFont(new java.awt.Font("Trebuchet MS", 0, 11)); // NOI18N
        txtRate.setText("0.0");
        txtRate.setToolTipText("");

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addGap(27, 27, 27)
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel46)
                            .addComponent(jLabel84))
                        .addGap(6, 6, 6)
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel34)
                            .addComponent(jLabel33)
                            .addComponent(jLabel59)
                            .addComponent(jLabel30, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel1))
                        .addGap(10, 10, 10)
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel6Layout.createSequentialGroup()
                                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtfname, javax.swing.GroupLayout.PREFERRED_SIZE, 169, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtlname, javax.swing.GroupLayout.PREFERRED_SIZE, 207, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtcustcode, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtCname, javax.swing.GroupLayout.PREFERRED_SIZE, 207, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jLabel51, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabel52)))
                            .addComponent(txtRate, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel43)
                            .addComponent(jLabel42)
                            .addComponent(jLabel41)
                            .addComponent(jLabel40)
                            .addComponent(jLabel39)
                            .addComponent(jLabel37)
                            .addComponent(jLabel36))
                        .addGap(7, 7, 7)
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtCcc, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(txtCemail, javax.swing.GroupLayout.DEFAULT_SIZE, 149, Short.MAX_VALUE)
                                .addComponent(txtaltcontact, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(txtaltphone, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(txtCfax, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(txtCphone, javax.swing.GroupLayout.Alignment.LEADING))
                            .addComponent(txtcontact, javax.swing.GroupLayout.PREFERRED_SIZE, 173, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addGap(39, 39, 39)
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel6Layout.createSequentialGroup()
                                .addComponent(jButton7)
                                .addGap(11, 11, 11)
                                .addComponent(jButton8)
                                .addGap(7, 7, 7)
                                .addComponent(jButton9))
                            .addComponent(jLabel35)
                            .addGroup(jPanel6Layout.createSequentialGroup()
                                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 276, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(86, 86, 86)
                                .addComponent(jLabel58)))))
                .addContainerGap(28, Short.MAX_VALUE))
        );

        jPanel6Layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {txtCcc, txtCemail, txtCfax, txtCphone, txtaltcontact, txtaltphone, txtcontact});

        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel46, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel30, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(txtCname, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel36, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel51, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(txtcontact, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel59, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(txtcustcode, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel37, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(txtCphone, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel52, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel84, javax.swing.GroupLayout.Alignment.TRAILING))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel33, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(txtfname, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel39, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(txtCfax, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel34, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(txtlname, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel40, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(txtaltphone, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jLabel41, javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(txtaltcontact, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel1)
                        .addComponent(txtRate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(6, 6, 6)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel42, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(txtCemail, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtCcc, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel43, javax.swing.GroupLayout.Alignment.TRAILING))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel58))
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(jLabel35)
                        .addGap(6, 6, 6)
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton7)
                    .addComponent(jButton8)
                    .addComponent(jButton9))
                .addGap(20, 20, 20))
        );

        jTabbedPane1.addTab("Address Info.", jPanel6);

        jLabel32.setFont(new java.awt.Font("Trebuchet MS", 0, 11)); // NOI18N
        jLabel32.setText("Terms :");

        txtterms.setColumns(20);
        txtterms.setFont(new java.awt.Font("Trebuchet MS", 0, 11)); // NOI18N
        txtterms.setRows(5);
        jScrollPane4.setViewportView(txtterms);

        jLabel44.setFont(new java.awt.Font("Trebuchet MS", 0, 11)); // NOI18N
        jLabel44.setText("Comment :");

        txtcomment.setColumns(20);
        txtcomment.setFont(new java.awt.Font("Trebuchet MS", 0, 11)); // NOI18N
        txtcomment.setRows(5);
        jScrollPane5.setViewportView(txtcomment);

        jLabel45.setFont(new java.awt.Font("Trebuchet MS", 0, 11)); // NOI18N
        jLabel45.setText("Send Method :");

        cmbmail.setFont(new java.awt.Font("Trebuchet MS", 0, 11)); // NOI18N
        cmbmail.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Mail", "Email", " " }));

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel32)
                    .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 487, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel44)
                    .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 434, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addComponent(jLabel45)
                        .addGap(10, 10, 10)
                        .addComponent(cmbmail, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE))))
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addComponent(jLabel32)
                .addGap(6, 6, 6)
                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(5, 5, 5)
                .addComponent(jLabel44)
                .addGap(15, 15, 15)
                .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(12, 12, 12)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(jLabel45))
                    .addComponent(cmbmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );

        jTabbedPane1.addTab("Additional Info.", jPanel7);

        jButton10.setFont(new java.awt.Font("Trebuchet MS", 0, 11)); // NOI18N
        jButton10.setText("Ok");
        jButton10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton10ActionPerformed(evt);
            }
        });

        jButton11.setFont(new java.awt.Font("Trebuchet MS", 0, 11)); // NOI18N
        jButton11.setText("Cancel");
        jButton11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton11ActionPerformed(evt);
            }
        });

        jButton12.setFont(new java.awt.Font("Trebuchet MS", 0, 11)); // NOI18N
        jButton12.setText("Exit");
        jButton12.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton12ActionPerformed(evt);
            }
        });

        cmbCustname.getEditor().getEditorComponent().addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) { 
                cmbCustnameKeyReleased(evt);
            } });

            javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
            jPanel4.setLayout(jPanel4Layout);
            jPanel4Layout.setHorizontalGroup(
                jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel4Layout.createSequentialGroup()
                    .addGap(10, 10, 10)
                    .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel4Layout.createSequentialGroup()
                            .addComponent(jLabel27)
                            .addGap(10, 10, 10)
                            .addComponent(cmbCustname, javax.swing.GroupLayout.PREFERRED_SIZE, 266, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jPanel4Layout.createSequentialGroup()
                            .addComponent(jLabel28, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(10, 10, 10)
                            .addComponent(txtbalance, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(10, 10, 10)
                            .addComponent(jLabel29)
                            .addGap(10, 10, 10)
                            .addComponent(jDateChooser3, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                    .addContainerGap()
                    .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(jSeparator1, javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel4Layout.createSequentialGroup()
                            .addComponent(jTabbedPane1)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jButton10, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jButton11)
                                .addComponent(jButton12, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGap(18, 18, 18))
            );

            jPanel4Layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {jButton10, jButton11, jButton12});

            jPanel4Layout.setVerticalGroup(
                jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel4Layout.createSequentialGroup()
                    .addGap(20, 20, 20)
                    .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel4Layout.createSequentialGroup()
                            .addGap(6, 6, 6)
                            .addComponent(jLabel27))
                        .addComponent(cmbCustname, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGap(6, 6, 6)
                    .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel4Layout.createSequentialGroup()
                            .addGap(6, 6, 6)
                            .addComponent(jLabel28))
                        .addComponent(txtbalance, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(jPanel4Layout.createSequentialGroup()
                            .addGap(6, 6, 6)
                            .addComponent(jLabel29))
                        .addGroup(jPanel4Layout.createSequentialGroup()
                            .addGap(1, 1, 1)
                            .addComponent(jDateChooser3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGap(15, 15, 15)
                    .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel4Layout.createSequentialGroup()
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 22, Short.MAX_VALUE)
                            .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(20, 20, 20))
                        .addGroup(jPanel4Layout.createSequentialGroup()
                            .addGap(43, 43, 43)
                            .addComponent(jButton10)
                            .addGap(4, 4, 4)
                            .addComponent(jButton11)
                            .addGap(6, 6, 6)
                            .addComponent(jButton12)
                            .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
            );

            jPanel4Layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {jButton10, jButton11, jButton12});

            getContentPane().add(jPanel4, java.awt.BorderLayout.CENTER);

            pack();
        }// </editor-fold>//GEN-END:initComponents

    public void formload(String userid){
        this.userid=userid;
         try{
         if(company==null||!company.isInstalled()){
            company=AutoCompleteSupport.install(cmbCustname, GlazedLists.eventListOf(sup.getElements(company())));
            
         }
         }catch(Exception ex){
             errorFields = new JLabel("<HTML><FONT COLOR = BLUE>'"+ex.getMessage()+"'</FONT></HTML>");
             JOptionPane.showMessageDialog(null,errorFields,"DMS",JOptionPane.ERROR_MESSAGE);                  
         }
    }
    
    private DefaultComboBoxModel company () {                 
       int i=0;
       DefaultComboBoxModel tmodel =new DefaultComboBoxModel();
       org.hibernate.Session session = HibernateUtil.getSessionFactory().openSession();
      try {        
           session.beginTransaction();
           Query q = session.createQuery("from DtFactory");
           List auth=q.list();
           Iterator iterator=auth.iterator();
           id=new Object[auth.size()];
           while(iterator.hasNext()){ 
                   DtFactory supp=(DtFactory)iterator.next();
                   tmodel.addElement(supp.getCompanyName()); 
                   id[i]=supp.getId();
                   i++;         
           }
           session.getTransaction().commit();
         }catch (HibernateException he) {
                 errorFields = new JLabel("<HTML><FONT COLOR = Blue>'"+he.getStackTrace()+"'</FONT></HTML>");
                 JOptionPane.showMessageDialog(null,errorFields,"DMS",JOptionPane.ERROR_MESSAGE);

         }finally {
             session.close(); 
         }
          return tmodel;
    }
    
    public void companySearch(int supplierid ){
       Session session = HibernateUtil.getSessionFactory().openSession();
       Transaction tx = null;
      try{
         tx = session.beginTransaction();
          comp= (DtFactory)session.get(DtFactory.class, supplierid);
         if(comp!=null){
            fillCustFields();          
         }else
             CustresetFields();
         tx.commit();
      }catch (HibernateException e) {
         if (tx!=null) tx.rollback();
             errorFields = new JLabel("<HTML><FONT COLOR = Blue>'"+e.getMessage()+"'</FONT></HTML>");
             JOptionPane.showMessageDialog(null,errorFields,"DMS",JOptionPane.ERROR_MESSAGE);
      }finally {
         session.close(); 
      }
   }
    
    public void CustresetFields(){
//    String scode="100"+String.valueOf(main.newpatient("dt_customerdetails")+1);
    txtcustcode.setText("");
    txtCname.setText("");
    txtfname.setText("");
    txtlname.setText("");
    txtcontact.setText("");
    txtRate.setText("0.0");
    txtCphone.setText("");
    txtCfax.setText("");
    txtaltphone.setText("");
    txtaltcontact.setText("");
    txtCemail.setText("");
    txtCcc.setText("");
    txtABill.setText("");
    txtterms.setText("");
    txtcomment.setText("");
    cmbmail.setSelectedIndex(0);    
  }
   public void enableCustFields(boolean state ){
    txtcustcode.setEnabled(state);
    txtCname.setEnabled(state);
    txtfname.setEnabled(state);
    txtlname.setEnabled(state);
    txtcontact.setEnabled(state);
    txtCphone.setEnabled(state);
    txtCfax.setEnabled(state);
    txtaltphone.setEnabled(state);
    txtaltcontact.setEnabled(state);
    txtCemail.setEnabled(state);
    txtCcc.setEnabled(state);
    txtABill.setEnabled(state);
    txtterms.setEnabled(state);
    txtcomment.setEnabled(state);
    cmbmail.setSelectedIndex(0); 
    txtRate.setEnabled(state);
} 
public int fillCustFields(){
    txtcustcode.setText(sup.getIntValue(comp.getId()));
    txtCname.setText(comp.getCompanyName());
    txtfname.setText(comp.getFname());
    txtlname.setText(comp.getLname());
    txtRate.setText(String.valueOf(comp.getRate()));
    txtcontact.setText(comp.getContact());
    txtCphone.setText(comp.getPhone());
    txtCfax.setText(comp.getFax());
    txtaltphone.setText(comp.getAphone());
    txtaltcontact.setText(comp.getAcontact());
    txtCemail.setText(comp.getEmail());
    txtCcc.setText(comp.getCc());
    txtABill.setText(comp.getBillTo());
    txtterms.setText(comp.getTerms());
    txtcomment.setText(comp.getComments());
    cmbmail.setSelectedItem(comp.getSendmethod());
    return 0;
}

public boolean add_company(String companyName, String fname, String lname, String contact, String phone, String fax, String aphone, String acontact, String email, String cc, String billTo, String terms, String comments, String sendmethod,double rate){
      Session session = HibernateUtil.getSessionFactory().openSession();      
      Transaction tx = null;
      boolean state=false;
      try{          
            DtFactory supp=new DtFactory(companyName, fname, lname, contact, phone, fax, aphone, acontact, email, cc, billTo, terms, comments, sendmethod,rate);
           
            tx = session.beginTransaction();
            Query q = session.createQuery("FROM DtFactory supplier WHERE supplier.companyName=:name");
            q.setParameter("name", companyName);
            List results=q.list();
            Iterator iterator=results.iterator();         
         if(!iterator.hasNext()){
            session.save(supp);
            errorFields = new JLabel("<HTML><FONT COLOR = Blue>new company added successfully</FONT></HTML>");
         }
         else{
             supp=(DtFactory)results.get(0); 
             supp.setAcontact(acontact);
             supp.setAphone(aphone);
             supp.setBillTo(billTo);
             supp.setCc(cc);
             supp.setComments(comments);
             supp.setCompanyName(companyName);
             supp.setContact(contact);
             supp.setEmail(email);
             supp.setFax(fax);
             supp.setFname(fname);
             supp.setLname(lname);
             supp.setPhone(phone);
             supp.setRate(rate);
             supp.setSendmethod(sendmethod);
             supp.setTerms(terms);
             
//             DtSuppliers suppli=new DtSuppliers(companyName, fname, lname, contact, phone, fax, aphone, acontact, email, cc, billTo, terms, comments, sendmethod);
             session.update(supp);  
             errorFields = new JLabel("<HTML><FONT COLOR = Blue>new company updated successfully</FONT></HTML>");
         }
            tx.commit();            
            JOptionPane.showMessageDialog(null,errorFields,"DMS",JOptionPane.ERROR_MESSAGE);
            state=true;
            
      }catch (HibernateException e) {
         if (tx!=null) tx.rollback();
             e.printStackTrace(); 
      }finally {
         session.flush();
         session.close(); 
      }
      return state;
   }

private boolean deleteCompany(int id){
       org.hibernate.Session session = HibernateUtil.getSessionFactory().openSession();
       Transaction tx = null;
       boolean status=false;
      try{
         tx = session.beginTransaction();
         DtFactory factory = (DtFactory)session.get(DtFactory.class, id); 
         if(factory!=null)
            session.delete(factory);
         tx.commit();
         status=true;
      }catch (HibernateException e) {
         if (tx!=null) tx.rollback();
             errorFields = new JLabel("<HTML><FONT COLOR = BLUE>'"+e.getMessage()+"'</FONT></HTML>");
             JOptionPane.showMessageDialog(null,errorFields,"DMS",JOptionPane.ERROR_MESSAGE); 
      }finally {
         session.close(); 
      }
     return status;
   }
    
    private void cmbCustnameItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cmbCustnameItemStateChanged
        // TODO add your handling code here:
        try{
            String type=sup.getValue(cmbCustname.getSelectedItem());
            if(cmbCustname.getSelectedIndex()!=-1) {
                int customerid=Integer.parseInt(sup.getIntValue(id[cmbCustname.getSelectedIndex()]));
                companySearch(customerid);
                //                customer.getCustomerBal(customerid);
                //                txtbalance.setText(customer.getBal());
                enableCustFields(false);
            }
        }catch(Exception ex){

        }
    }//GEN-LAST:event_cmbCustnameItemStateChanged

    private void cmbCustnameKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_cmbCustnameKeyReleased
        // TODO add your handling code here:
        try{
            String Pid=cmbCustname.getEditor().getItem().toString();
            //            cmbCustname.setModel(customer.searchCustomer("1",Pid));
            cmbCustname.showPopup();
            cmbCustname.setSelectedItem(Pid);
        }catch(Exception ex){

        }
    }//GEN-LAST:event_cmbCustnameKeyReleased

    private void jDateChooser3PropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_jDateChooser3PropertyChange
        // TODO add your handling code here:
        if(cmbCustname.getSelectedIndex()!=-1) {
            //            String customerid=customer.Uid()[cmbCustname.getSelectedIndex()];
            //            String date=new SimpleDateFormat("dd-MM-yyyy").format(jDateChooser3.getDate());
            //            customer.getCustDateBal(customerid, date);
            //            txtbalance.setText(customer.getBal());
            cmbCustname.setSelectedIndex(-1);
        }
    }//GEN-LAST:event_jDateChooser3PropertyChange

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
        // TODO add your handling code here:
        String scode="0";
        cmbCustname.setSelectedIndex(-1);
        txtbalance.setText("0.00");
        CustresetFields();
        enableCustFields(true);
        scode= String.valueOf(new rowcount().row_count(DtFactory.class)+1);    
        txtcustcode.setText(scode);
    }//GEN-LAST:event_jButton7ActionPerformed

    private void jButton9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton9ActionPerformed
        // TODO add your handling code here:
        String custcode=txtcustcode.getText();
        if(custcode.equals("")){
            JLabel errorFields = new JLabel("<HTML><FONT COLOR = BLUE>Record Not Found,Please Select a Record!.</FONT></HTML>");
            JOptionPane.showMessageDialog(null,errorFields,"Dairy management system",JOptionPane.INFORMATION_MESSAGE);
        }else{
                int id=comp.getId();
                deleteCompany(id);
        }
    }//GEN-LAST:event_jButton9ActionPerformed

    private void jButton8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton8ActionPerformed
        // TODO add your handling code here:
                enableCustFields(true);
    }//GEN-LAST:event_jButton8ActionPerformed

    private void jButton10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton10ActionPerformed
        // TODO add your handling code here:
        String custcode=txtcustcode.getText().trim();
        String companyname=txtCname.getText().trim();
        String fname=txtfname.getText().trim();
        String lname=txtfname.getText().trim();
        String contact=txtcontact.getText().trim();
        String phone=txtCphone.getText().trim();
        String fax=txtCfax.getText().trim();
        String aphone=txtaltphone.getText().trim();
        String acontact=txtaltcontact.getText().trim();
        String email=txtCemail.getText().trim();
        String cc=txtCcc.getText().trim();
        String billto=txtABill.getText().trim();
        String terms=txtterms.getText().trim();
        String comments=txtcomment.getText().trim();
        String sendmethod=cmbmail.getSelectedItem().toString().trim();
        double rate=Double.parseDouble(sup.getCostValue(txtRate.getText()));
        if(!companyname.equals("")||!contact.equals("")||!phone.equals("")){
            this.add_company(companyname, fname, lname, contact, phone, fax, aphone, acontact, email, cc, billto, terms, comments, sendmethod,rate);
        }else{
            JLabel errorFields = new JLabel("<HTML><FONT COLOR = blue>Please make sure that required fileds are filled!.</FONT></HTML>");
            JOptionPane.showMessageDialog(null,errorFields,"Laundry Management System",JOptionPane.INFORMATION_MESSAGE);
        }
    }//GEN-LAST:event_jButton10ActionPerformed

    private void jButton11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton11ActionPerformed
        // TODO add your handling code here:
                CustresetFields();
    }//GEN-LAST:event_jButton11ActionPerformed

    private void jButton12ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton12ActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
    }//GEN-LAST:event_jButton12ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox cmbCustname;
    private javax.swing.JComboBox cmbmail;
    private javax.swing.JButton jButton10;
    private javax.swing.JButton jButton11;
    private javax.swing.JButton jButton12;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton8;
    private javax.swing.JButton jButton9;
    private com.toedter.calendar.JDateChooser jDateChooser3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JLabel jLabel34;
    private javax.swing.JLabel jLabel35;
    private javax.swing.JLabel jLabel36;
    private javax.swing.JLabel jLabel37;
    private javax.swing.JLabel jLabel39;
    private javax.swing.JLabel jLabel40;
    private javax.swing.JLabel jLabel41;
    private javax.swing.JLabel jLabel42;
    private javax.swing.JLabel jLabel43;
    private javax.swing.JLabel jLabel44;
    private javax.swing.JLabel jLabel45;
    private javax.swing.JLabel jLabel46;
    private javax.swing.JLabel jLabel51;
    private javax.swing.JLabel jLabel52;
    private javax.swing.JLabel jLabel58;
    private javax.swing.JLabel jLabel59;
    private javax.swing.JLabel jLabel84;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTextArea txtABill;
    private javax.swing.JTextField txtCcc;
    private javax.swing.JTextField txtCemail;
    private javax.swing.JTextField txtCfax;
    private javax.swing.JTextField txtCname;
    private javax.swing.JTextField txtCphone;
    private javax.swing.JTextField txtRate;
    private javax.swing.JTextField txtaltcontact;
    private javax.swing.JTextField txtaltphone;
    private javax.swing.JTextField txtbalance;
    private javax.swing.JTextArea txtcomment;
    private javax.swing.JTextField txtcontact;
    private javax.swing.JTextField txtcustcode;
    private javax.swing.JTextField txtfname;
    private javax.swing.JTextField txtlname;
    private javax.swing.JTextArea txtterms;
    // End of variables declaration//GEN-END:variables
}
