/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ui;

import classes.DateEditor;
import classes.DecimalFormatRenderer;
import classes.SpinnerEditor;
import classes.TextFieldEditor;
import classes.comboCellEditor;
import classes.superCls;
import custom_jPanels.RoundRectGradientPanel;
import farm.entity.DtInventory;
import farm.entity.DtInventoryItemlist;
import farm.entity.DtStockMovement;
import farmTech.util.HibernateUtil;
import java.awt.CardLayout;
import java.awt.Container;
import java.awt.event.ItemEvent;
import java.awt.event.ItemListener;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.Iterator;
import java.util.List;
import java.util.Locale;
import javax.swing.BorderFactory;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JComboBox;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.event.TableModelEvent;
import javax.swing.event.TableModelListener;
import models.inventoryRecord;
import models.inventoryTableModel;
import org.hibernate.HibernateException;
import org.hibernate.Query;
import org.hibernate.Session;
import org.hibernate.Transaction;
//import org.jdesktop.swingx.table.DatePickerCellEditor;

/**
 *
 * @author Kent
 */
public class itemRecvPane extends javax.swing.JFrame {

    private final JComboBox cmbdrug=new JComboBox();
    private DefaultComboBoxModel drug_model=new DefaultComboBoxModel();
    private final TextFieldEditor inte=new TextFieldEditor("integer");
    private final TextFieldEditor str=new TextFieldEditor("string");
    private JLabel errorFields;
    private String adj_code="ADJO8291";
    private String[] unit,description,supplier,productCode,category;
    private Double[] discount,vat,buyingprice,sellingprice;
//    InteractiveTableModelListener tablemodel= new InteractiveTableModelListener();
    /**
     * Creates new form itemRecvPane
     */
    
    private inventoryTableModel inventory_model;
    private DefaultComboBoxModel adjCode_model=new DefaultComboBoxModel( new String[] {"PO Receive","Returned","Cycle Count", "Assembled","Cancelledd Shipment","Product of disAssembly","Store Appointment Receive"});
//    pharmacycls pharm=new pharmacycls();
    superCls sup=new superCls();
    public itemRecvPane() {
        initComponents();
    }
    public void formload(){
         
      String header[]={"Item Name","Item Id","Units","Wrhe Location","Lot/Serial No","Exp.Date","Reference","Unit Cost","Unit Price"};
      inventory_model=new inventoryTableModel(header);  
      inventory_model.addTableModelListener(new InteractiveTableModelListener());
      jTable1.setModel(inventory_model);
      jTable1.putClientProperty("terminateEditOnFocusLost", Boolean.TRUE);
      jTable1.setRowHeight(20);
      cmb_code.setModel(adjCode_model);
      
      cmb_code.setSelectedIndex(-1);  
      drug_model=product_list();
    }
    
    public class InteractiveTableModelListener implements TableModelListener{
     @Override     
     public void tableChanged(TableModelEvent evt) {
             int column = evt.getColumn();
             int row = evt.getFirstRow();
         if (evt.getType() == TableModelEvent.UPDATE) {
             String productcode=sup.getValue(inventory_model.getValueAt(row, 1));
             double cost=Double.parseDouble(sup.getCostValue(inventory_model.getValueAt(row, 7)));
             double price=Double.parseDouble(sup.getCostValue(inventory_model.getValueAt(row, 8)));
             if(column==7 && !productcode.equals("") && cost!=0.0)
                 FindProduct(1,productcode, cost);
             if(column==8 && !productcode.equals("") && price!=0.0)
                 FindProduct(2,productcode, price);             
         }
         if (evt.getType() == TableModelEvent.DELETE) {
             
         }         
         if (evt.getType() == TableModelEvent.INSERT) {
             
         }
     }
 }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new RoundRectGradientPanel();
        jToolBar1 = new javax.swing.JToolBar();
        jButton8 = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton9 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jDateChooser1 = new com.toedter.calendar.JDateChooser();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jSeparator2 = new javax.swing.JSeparator();
        jButton4 = new javax.swing.JButton();
        cmb_code = new javax.swing.JComboBox();
        jToolBar2 = new javax.swing.JToolBar();
        jButton5 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jButton7 = new javax.swing.JButton();

        setTitle("Item Direct Receive");

        jToolBar1.setFloatable(false);
        jToolBar1.setRollover(true);
        jToolBar1.setOpaque(false);

        jButton8.setFont(new java.awt.Font("Trebuchet MS", 0, 11)); // NOI18N
        jButton8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/folder-new-24.png"))); // NOI18N
        jButton8.setText("Add New");
        jButton8.setFocusable(false);
        jButton8.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton8.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jButton8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton8ActionPerformed(evt);
            }
        });
        jToolBar1.add(jButton8);

        jButton1.setFont(new java.awt.Font("Trebuchet MS", 0, 11)); // NOI18N
        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/labels-24.png"))); // NOI18N
        jButton1.setText("  Labels  ");
        jButton1.setFocusable(false);
        jButton1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton1.setIconTextGap(2);
        jButton1.setOpaque(false);
        jButton1.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jToolBar1.add(jButton1);

        jButton2.setFont(new java.awt.Font("Trebuchet MS", 0, 11)); // NOI18N
        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/clipboard-list-24.png"))); // NOI18N
        jButton2.setText("  Stow List  ");
        jButton2.setFocusable(false);
        jButton2.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton2.setIconTextGap(2);
        jButton2.setOpaque(false);
        jButton2.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jToolBar1.add(jButton2);

        jButton3.setFont(new java.awt.Font("Trebuchet MS", 0, 11)); // NOI18N
        jButton3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/barcode-24.png"))); // NOI18N
        jButton3.setText("  Barcodes  ");
        jButton3.setFocusable(false);
        jButton3.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton3.setIconTextGap(2);
        jButton3.setOpaque(false);
        jButton3.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jToolBar1.add(jButton3);

        jButton9.setFont(new java.awt.Font("Trebuchet MS", 0, 11)); // NOI18N
        jButton9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/exit-24.png"))); // NOI18N
        jButton9.setText("Exit");
        jButton9.setFocusable(false);
        jButton9.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton9.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jButton9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton9ActionPerformed(evt);
            }
        });
        jToolBar1.add(jButton9);

        jLabel1.setFont(new java.awt.Font("Trebuchet MS", 0, 11)); // NOI18N
        jLabel1.setText("Adj. Code :");

        jLabel2.setFont(new java.awt.Font("Trebuchet MS", 0, 11)); // NOI18N
        jLabel2.setText("Receipt Date :");

        jDateChooser1.setDate(new Date());
        jDateChooser1.setDateFormatString("dd-MM-yyyy");
        jDateChooser1.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                jDateChooser1PropertyChange(evt);
            }
        });

        jTable1.setAutoCreateRowSorter(true);
        jTable1.setFont(new java.awt.Font("Trebuchet MS", 0, 11)); // NOI18N
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jTable1.setGridColor(new java.awt.Color(204, 204, 204));
        jTable1.setRowHeight(19);
        jScrollPane1.setViewportView(jTable1);

        jSeparator2.setForeground(new java.awt.Color(51, 51, 255));

        jButton4.setFont(new java.awt.Font("Trebuchet MS", 0, 11)); // NOI18N
        jButton4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/database_save.png"))); // NOI18N
        jButton4.setText("Receive");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        cmb_code.setFont(new java.awt.Font("Trebuchet MS", 0, 11)); // NOI18N
        cmb_code.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cmb_codeItemStateChanged(evt);
            }
        });

        jToolBar2.setFloatable(false);
        jToolBar2.setOrientation(javax.swing.SwingConstants.VERTICAL);
        jToolBar2.setRollover(true);
        jToolBar2.setName(""); // NOI18N
        jToolBar2.setOpaque(false);

        jButton5.setFont(new java.awt.Font("Trebuchet MS", 0, 11)); // NOI18N
        jButton5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/plus_16.png"))); // NOI18N
        jButton5.setText("   Add    ");
        jButton5.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton5.setIconTextGap(2);
        jButton5.setName(""); // NOI18N
        jButton5.setOpaque(false);
        jButton5.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        jToolBar2.add(jButton5);

        jButton6.setFont(new java.awt.Font("Trebuchet MS", 0, 11)); // NOI18N
        jButton6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/search-20.png"))); // NOI18N
        jButton6.setText(" Search ");
        jButton6.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton6.setIconTextGap(2);
        jButton6.setName(""); // NOI18N
        jButton6.setOpaque(false);
        jButton6.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });
        jToolBar2.add(jButton6);

        jButton7.setFont(new java.awt.Font("Trebuchet MS", 0, 11)); // NOI18N
        jButton7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/delete_16.png"))); // NOI18N
        jButton7.setText(" remove");
        jButton7.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton7.setIconTextGap(2);
        jButton7.setName(""); // NOI18N
        jButton7.setOpaque(false);
        jButton7.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });
        jToolBar2.add(jButton7);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(7, 7, 7)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jSeparator2)
                    .addComponent(jToolBar1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jToolBar2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 773, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(4, 4, 4)
                        .addComponent(cmb_code, javax.swing.GroupLayout.PREFERRED_SIZE, 186, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(74, 74, 74)
                        .addComponent(jLabel2)
                        .addGap(4, 4, 4)
                        .addComponent(jDateChooser1, javax.swing.GroupLayout.PREFERRED_SIZE, 189, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(10, 10, 10)
                        .addComponent(jButton4)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addComponent(jToolBar1, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(15, 15, 15)
                        .addComponent(jLabel1))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(12, 12, 12)
                        .addComponent(cmb_code, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(15, 15, 15)
                        .addComponent(jLabel2))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(11, 11, 11)
                        .addComponent(jDateChooser1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 2, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 332, Short.MAX_VALUE)
                    .addComponent(jToolBar2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        getContentPane().add(jPanel1, java.awt.BorderLayout.PAGE_START);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        // TODO add your handling code here:
        if(!inventory_model.hasEmptyRow()){
            cmbdrug.setModel(product_list());
            cmbdrug.setBorder (BorderFactory.createEmptyBorder());
//            Date date=new Date();
            SimpleDateFormat formatter = new SimpleDateFormat("yyyy-MM-dd", Locale.ENGLISH);
            Date date=sup.sqlDate(new SimpleDateFormat("dd-MM-yyyy").format(new Date()));
//            DatePickerCellEditor datePicker = new DatePickerCellEditor(formatter);
//            datePicker.setClickCountToStart(1);
            
//            cmbdrug.setEditable(true);
            inventory_model.addEmptyRow(new inventoryRecord("","",0,"","",date,"",00.00,00.00));
            jTable1.getColumnModel().getColumn(0).setCellEditor(new comboCellEditor(cmbdrug));
            jTable1.getColumnModel().getColumn(1).setCellEditor(str);
            jTable1.getColumnModel().getColumn(2).setCellEditor(inte);
            jTable1.getColumnModel().getColumn(3).setCellEditor(str);
            jTable1.getColumnModel().getColumn(4).setCellEditor(str);
            jTable1.getColumnModel().getColumn(5).setCellEditor(new SpinnerEditor());
            jTable1.getColumnModel().getColumn(6).setCellEditor(str);
            jTable1.getColumnModel().getColumn(7).setCellEditor(inte);
            jTable1.getColumnModel().getColumn(8).setCellEditor(inte);
            
            jTable1.getColumnModel().getColumn(7).setCellRenderer(new DecimalFormatRenderer());
            jTable1.getColumnModel().getColumn(8).setCellRenderer(new DecimalFormatRenderer());
//            jTable1.setDefaultEditor(Date.class, new JDateChooserCellEditor());
            highlightLastRow();
            
            cmbdrug.addItemListener(new ItemListener() {
            @Override
            public void itemStateChanged(ItemEvent e) {
                int idx=cmbdrug.getSelectedIndex();
                int row=jTable1.getSelectedRow();
                if (e.getStateChange() == ItemEvent.SELECTED && idx!=-1) {  
                    
                    String drugname=sup.getValue(cmbdrug.getSelectedItem());
                    inventory_model.setValueAt(productCode[idx], row, 1);
                    inventory_model.setValueAt(buyingprice[idx], row, 7);
                    inventory_model.setValueAt(sellingprice[idx], row, 8);
                    inventory_model.setValueAt(adj_code, row, 6);
                }
            }
        });
        }
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        // TODO add your handling code here:
        medicine_table meds=new medicine_table();
        meds.formload();
        JOptionPane.showOptionDialog(null, meds.getContentPane(),"Inventory Item List", JOptionPane.DEFAULT_OPTION,JOptionPane.PLAIN_MESSAGE, null, new Object[]{}, null);
//        String description=meds.getDescription();
        String productcode=sup.getValue(meds.getProductCode());
        String item_name=meds.getProductName();
        double vat1=meds.getVat();
        double cost=meds.getCost();
        double price=meds.getSp();
//        double discount1=meds.getDiscount();
//        int avail=pharm.drug_stock(productcode);

        if(!productcode.equals("") && !inventory_model.hasEmptyRow()){
            cmbdrug.setModel(product_list());
            cmbdrug.setBorder (BorderFactory.createEmptyBorder());
            cmbdrug.setEditable(false);
//            String date=new SimpleDateFormat("dd-MM-yyyy").format(new Date());
            Date date=new Date();
//            cmbdrug.setEditable(true);
            inventory_model.addEmptyRow(new inventoryRecord(item_name,productcode,0,"","",date,adj_code,cost,price));
            jTable1.getColumnModel().getColumn(0).setCellEditor(new comboCellEditor(cmbdrug));
            jTable1.getColumnModel().getColumn(1).setCellEditor(str);
            jTable1.getColumnModel().getColumn(2).setCellEditor(inte);
            jTable1.getColumnModel().getColumn(3).setCellEditor(str);
            jTable1.getColumnModel().getColumn(4).setCellEditor(str);
            jTable1.getColumnModel().getColumn(5).setCellEditor(new DateEditor());
            jTable1.getColumnModel().getColumn(6).setCellEditor(str);
            jTable1.getColumnModel().getColumn(7).setCellEditor(inte);
            jTable1.getColumnModel().getColumn(7).setCellRenderer(new DecimalFormatRenderer());
            jTable1.getColumnModel().getColumn(8).setCellRenderer(new DecimalFormatRenderer());
            highlightLastRow();
        }
    }//GEN-LAST:event_jButton6ActionPerformed

    private void jDateChooser1PropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_jDateChooser1PropertyChange
        // TODO add your handling code here:
    }//GEN-LAST:event_jDateChooser1PropertyChange

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
        // TODO add your handling code here:
        int row=jTable1.getSelectedRow();
        if(row!=-1)
           inventory_model.removeRow(row);
        else{
           errorFields = new JLabel("<HTML><FONT COLOR = BLUE>Please Select an Item To Remove</FONT></HTML>");
           JOptionPane.showMessageDialog(null,errorFields,"Clinic Management System",JOptionPane.ERROR_MESSAGE); 
        }
    }//GEN-LAST:event_jButton7ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
        boolean status=true;
        String date=new SimpleDateFormat("dd-MM-yyyy").format(jDateChooser1.getDate());
        for(int i=0; i<inventory_model.getRowCount(); i++){ 
            inventoryRecord rec=inventory_model.getRowValues(i);
            if(rec.getItemId().equals("")|| rec.getUnits()==0 || rec.getExpDate()==new Date())
                status=false;           
            }
        if(status){
            for(int i=0; i<inventory_model.getRowCount(); i++){
                inventoryRecord rec=inventory_model.getRowValues(i);
                String exp_date=new SimpleDateFormat("dd-MM-yyyy").format(rec.getExpDate());
                save(rec.getItemId(), "pharm_001", rec.getSerial(), rec.getItem(), rec.getLocation(), rec.getReference(), exp_date, rec.getUnits(), rec.getCost(), rec.getPrice(), date);
                status=true;
            }
        }else{
            errorFields = new JLabel("<HTML><FONT COLOR = BLUE>Please make sure Itemid, units and Expiry date(<>today date) fields are all filled correctly</FONT></HTML>");
            JOptionPane.showMessageDialog(null,errorFields,"Farm Management System",JOptionPane.ERROR_MESSAGE);  
        }
        if(status){
            errorFields = new JLabel("<HTML><FONT COLOR = BLUE>Items Entered successfully in Inventory stock</FONT></HTML>");
            JOptionPane.showMessageDialog(null,errorFields,"Farm Management System",JOptionPane.INFORMATION_MESSAGE);  
            inventory_model.clearAllRows();
        }
//        String itemId, String description, String serialNo, String itemName, String wrheLocation, String reference, String expDate, int units, double unitCost, double unitPrice, String date
    }//GEN-LAST:event_jButton4ActionPerformed

    private void cmb_codeItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cmb_codeItemStateChanged
        // TODO add your handling code here:
        int idx=cmbdrug.getSelectedIndex();
        if (evt.getStateChange() == ItemEvent.SELECTED && idx!=-1) {
            switch(idx){
                case 0:
                    adj_code="ADJO8291";
                    break;
                case 1:
                    adj_code="ADJO8202";
                    break;
                case 2:
                    adj_code="ADJO8393";
                    break;
                case 3:
                    adj_code="ADJO8494";
                    break;
                case 4:
                    adj_code="ADJO8575";
                    break;
                case 5:
                    adj_code="ADJO8686";
                    break;
                case 6:
                    adj_code="ADJO8207";
            }
        }
    }//GEN-LAST:event_cmb_codeItemStateChanged

    private void jButton8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton8ActionPerformed
        // TODO add your handling code here:
        inventory_model.clearAllRows();
    }//GEN-LAST:event_jButton8ActionPerformed

    private void jButton9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton9ActionPerformed
        // TODO add your handling code here:
//        String name=this.getParent().getComponent(1).getName();
        Container jpanel2=this.getContentPane().getParent();
        CardLayout cardmanager=(CardLayout)(jpanel2.getLayout());
        cardmanager.show(jpanel2,"card2");
    }//GEN-LAST:event_jButton9ActionPerformed

    public void save(String itemId, String description, String serialNo, String itemName, String wrheLocation, String reference, String expDate, int units, double unitCost, double unitPrice, String date){
      Session session = HibernateUtil.getSessionFactory().openSession();      
      Transaction tx = null;
//      state=false;
      try{   
            tx=session.beginTransaction();
            
            DtStockMovement stock = new DtStockMovement(itemId, units, 0, sup.sqlDate(date));
            DtInventory inventory=new DtInventory(itemId, description, serialNo, itemName, wrheLocation, reference, sup.sqlDate(expDate), units, unitCost, unitPrice,  sup.sqlDate(date));
            //update stock
            session.saveOrUpdate(stock);
            //save inventory
            inventory.setStock(stock);
            session.saveOrUpdate(inventory);
            tx.commit();
//            state=true;
         
      }catch (HibernateException e) {
         if (tx!=null) tx.rollback();
         e.printStackTrace();
      }finally {
         session.close(); 
      }
//      return state;
   }
    
    private void FindProduct(int val,String productcode, double amount){
       org.hibernate.Session session = HibernateUtil.getSessionFactory().openSession();
       Transaction tx = null;
       boolean status=false;
      try{
         tx = session.beginTransaction();
         Query q = session.getNamedQuery("DtInventoryItemlist.findByProductCode");
         q.setParameter("productCode", productcode);
         q.setCacheable(true);
         List<DtInventoryItemlist> product=q.list();           
         Iterator<DtInventoryItemlist> itr=product.iterator();             
         if(itr.hasNext()){
             DtInventoryItemlist prod=(DtInventoryItemlist)itr.next();
             if(val==1)
                  prod.setUnitCost(amount);
             else
                 prod.setUnitPrice(amount);
             session.update(prod);
         }
         tx.commit();
         status=true;
      }catch (HibernateException e) {
         if (tx!=null) tx.rollback();
             errorFields = new JLabel("<HTML><FONT COLOR = BLUE>'"+e.getMessage()+"'</FONT></HTML>");
             JOptionPane.showMessageDialog(null,errorFields,"Clinic Management System",JOptionPane.ERROR_MESSAGE); 
      }finally {
         session.close(); 
      }
   }
   
 public void highlightLastRow()
{
 int lastrow = inventory_model.getRowCount();
 if(lastrow!=0)
     jTable1.setRowSelectionInterval(lastrow - 1, lastrow - 1);
 else
    jTable1.setRowSelectionInterval(lastrow, lastrow); 
 jTable1.setColumnSelectionInterval(0, 0);
 }
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbu".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | javax.swing.UnsupportedLookAndFeelException ex) {
//            java.util.logging.Logger.getLogger(thi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                
                itemRecvPane app=new itemRecvPane();
                app.formload();
                app.setDefaultCloseOperation(EXIT_ON_CLOSE);
                app.setVisible(true);
            }
        });
    }

    public DefaultComboBoxModel product_list() {
    Session session = HibernateUtil.getSessionFactory().openSession();
    DefaultComboBoxModel tmodel=new DefaultComboBoxModel();
    try {
        session = HibernateUtil.getSessionFactory().openSession();
        String hql;        
        session.beginTransaction();
        hql="Select DISTINCT m.itemName, m.productCode, m.description, m.unitPrice, m.discount, m.vat, m.supplierCode, m.unitPrice, m.unitCost from DtInventoryItemlist m ORDER BY m.itemName ASC";
        Query q = session.createQuery(hql);
        q.setCacheable(true);
        List result = q.list();     
        productCode=new String[result.size()+1];
        description=new String[result.size()+1];
        sellingprice=new Double[result.size()+1];
        buyingprice=new Double[result.size()+1];
        discount=new Double[result.size()+1];
        vat=new Double[result.size()+1];
        tmodel.removeAllElements();
        tmodel.addElement("");
        for(Object o:result){
            Object[] collection = (Object[])o;
            String names=sup.getValue(collection[0]);
            tmodel.addElement(names);
            productCode[tmodel.getIndexOf(names)]=sup.getValue(collection[1]);
            description[tmodel.getIndexOf(names)]=sup.getValue(collection[2]);
            discount[tmodel.getIndexOf(names)]=Double.parseDouble(sup.getCostValue(collection[4]));
            vat[tmodel.getIndexOf(names)]=Double.parseDouble(sup.getCostValue(collection[5]));
            sellingprice[tmodel.getIndexOf(names)]=Double.parseDouble(sup.getCostValue(collection[7]));
            buyingprice[tmodel.getIndexOf(names)]=Double.parseDouble(sup.getCostValue(collection[8]));
            
        }
        session.getTransaction().commit();
    } catch (HibernateException he) {
        errorFields = new JLabel("<HTML><FONT COLOR = BLUE>'"+he.getMessage()+"'</FONT></HTML>");
        JOptionPane.showMessageDialog(null,errorFields,"Clinic Management System",JOptionPane.ERROR_MESSAGE); 
    }
    finally {
             session.close(); 
         }    
    return tmodel;
   }
    
    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox cmb_code;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton8;
    private javax.swing.JButton jButton9;
    private com.toedter.calendar.JDateChooser jDateChooser1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JTable jTable1;
    private javax.swing.JToolBar jToolBar1;
    private javax.swing.JToolBar jToolBar2;
    // End of variables declaration//GEN-END:variables
}
