/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * jframe_collection.java
 *
 * Created on Nov 6, 2013, 4:17:11 PM
 */
package ui;

import classes.ColumnResizer;
import classes.clsDate;
import classes.cls_farmer;
import classes.labelRenderer;
import classes.superCls;
import custom_jPanels.RoundRectGradientPanel;
import custom_jPanels.SimpleGradientPanel;
import farm.entity.DtDailycollection;
import farm.entity.DtFarmerdetails;
import farm.entity.DtMstock;
import farm.entity.DtPurchasesAccount;
import farmTech.util.HibernateUtil;
import java.text.SimpleDateFormat;
import java.util.Arrays;
import java.util.Date;
import java.util.Iterator;
import java.util.List;
import java.util.Vector;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.SwingUtilities;
import javax.swing.table.DefaultTableModel;
import org.hibernate.HibernateException;
import org.hibernate.Query;
import org.hibernate.Session;
import org.hibernate.Transaction;

/**
 *
 * @author KENT
 */
public class jframe_collection extends javax.swing.JInternalFrame {

    /** Creates new form jframe_collection */
    cls_farmer farmer;
    superCls sup=new superCls();
    clsDate dt=new clsDate();
    private String userid="";
    Date month_begin=null;
    private JLabel errorFields;
    private int reccode=0,id=0,stock_id=0,pid=0;
    private double rate=0.0,total=0.0;
    private DefaultTableModel farmer_model;
    public jframe_collection() {
        initComponents();
        farmer=new cls_farmer();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new RoundRectGradientPanel();
        jLabel1 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jTextField2 = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        txtwater = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        txtsnf = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        txtprotein = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        txtfat = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        txtfp = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        txtquantity = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        cmbSession = new javax.swing.JComboBox();
        jLabel14 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jSeparator1 = new javax.swing.JSeparator();
        jPanel2 = new SimpleGradientPanel();
        jLabel15 = new javax.swing.JLabel();
        lbl_Fid = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        lbl_age = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        lbl_Fname = new javax.swing.JLabel();
        lbl_sex = new javax.swing.JLabel();
        lbl_Fphone = new javax.swing.JLabel();
        lbl_Faddress = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jDateChooser1 = new com.toedter.calendar.JDateChooser();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jCheckBox1 = new javax.swing.JCheckBox();
        jButton3 = new javax.swing.JButton();
        jComboBox1 = new javax.swing.JComboBox();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();

        setClosable(true);
        setDefaultCloseOperation(javax.swing.WindowConstants.HIDE_ON_CLOSE);
        setIconifiable(true);
        setTitle("Daily Milk Collection");
        setFrameIcon(new javax.swing.ImageIcon(getClass().getResource("/images/ox-cow.png"))); // NOI18N

        jLabel1.setFont(new java.awt.Font("Trebuchet MS", 0, 11)); // NOI18N
        jLabel1.setText("Search Farmer: ");

        jTextField1.setFont(new java.awt.Font("Trebuchet MS", 0, 11)); // NOI18N
        jTextField1.setText("Type farmer name here");
        jTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1ActionPerformed(evt);
            }
        });
        jTextField1.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jTextField1FocusGained(evt);
            }
        });
        jTextField1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jTextField1KeyReleased(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Trebuchet MS", 0, 11)); // NOI18N
        jLabel2.setText("Farmer ID :");

        jTextField2.setFont(new java.awt.Font("Trebuchet MS", 0, 11)); // NOI18N
        jTextField2.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jTextField2FocusGained(evt);
            }
        });

        jButton1.setFont(new java.awt.Font("Trebuchet MS", 0, 11)); // NOI18N
        jButton1.setText("Search");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel7.setFont(new java.awt.Font("Trebuchet MS", 0, 11)); // NOI18N
        jLabel7.setText("Water :");

        txtwater.setFont(new java.awt.Font("Trebuchet MS", 0, 11)); // NOI18N
        txtwater.setText("0.00");
        txtwater.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtwaterFocusGained(evt);
            }
        });

        jLabel8.setFont(new java.awt.Font("Trebuchet MS", 0, 11)); // NOI18N
        jLabel8.setText("SNF:");

        txtsnf.setFont(new java.awt.Font("Trebuchet MS", 0, 11)); // NOI18N
        txtsnf.setText("0.00");
        txtsnf.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtsnfFocusGained(evt);
            }
        });

        jLabel9.setFont(new java.awt.Font("Trebuchet MS", 0, 11)); // NOI18N
        jLabel9.setText("Proteins:");

        txtprotein.setFont(new java.awt.Font("Trebuchet MS", 0, 11)); // NOI18N
        txtprotein.setText("0.00");
        txtprotein.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtproteinFocusGained(evt);
            }
        });

        jLabel10.setFont(new java.awt.Font("Trebuchet MS", 0, 11)); // NOI18N
        jLabel10.setText("FAT:");

        txtfat.setFont(new java.awt.Font("Trebuchet MS", 0, 11)); // NOI18N
        txtfat.setText("0.00");
        txtfat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtfatActionPerformed(evt);
            }
        });
        txtfat.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtfatFocusGained(evt);
            }
        });

        jLabel11.setFont(new java.awt.Font("Trebuchet MS", 0, 11)); // NOI18N
        jLabel11.setText("Freezing Pt.");

        txtfp.setFont(new java.awt.Font("Trebuchet MS", 0, 11)); // NOI18N
        txtfp.setText("0.00");
        txtfp.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtfpFocusGained(evt);
            }
        });

        jLabel12.setFont(new java.awt.Font("Trebuchet MS", 0, 11)); // NOI18N
        jLabel12.setText("Qty (Ltrs)");

        txtquantity.setFont(new java.awt.Font("Trebuchet MS", 0, 11)); // NOI18N
        txtquantity.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 51, 51)));
        txtquantity.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtquantityFocusGained(evt);
            }
        });

        jLabel13.setFont(new java.awt.Font("Trebuchet MS", 0, 11)); // NOI18N
        jLabel13.setText("Session :");

        cmbSession.setFont(new java.awt.Font("Trebuchet MS", 0, 11)); // NOI18N
        cmbSession.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "AM", "PM" }));

        jLabel14.setFont(new java.awt.Font("Trebuchet MS", 0, 11)); // NOI18N
        jLabel14.setText("Date :");

        jButton2.setFont(new java.awt.Font("Trebuchet MS", 0, 11)); // NOI18N
        jButton2.setText("Save");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jTable1.setFont(new java.awt.Font("Trebuchet MS", 0, 11)); // NOI18N
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jTable1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jTable1.setGridColor(new java.awt.Color(204, 204, 204));
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTable1);

        jLabel15.setFont(new java.awt.Font("Trebuchet MS", 0, 11)); // NOI18N
        jLabel15.setText("Age:");

        lbl_Fid.setFont(new java.awt.Font("Trebuchet MS", 0, 11)); // NOI18N

        jLabel6.setFont(new java.awt.Font("Trebuchet MS", 0, 11)); // NOI18N
        jLabel6.setText("Address :");

        jLabel3.setFont(new java.awt.Font("Trebuchet MS", 0, 11)); // NOI18N
        jLabel3.setText("Farmer ID :");

        jLabel4.setFont(new java.awt.Font("Trebuchet MS", 0, 11)); // NOI18N
        jLabel4.setText("Farmer Name :");

        lbl_age.setFont(new java.awt.Font("Trebuchet MS", 0, 11)); // NOI18N

        jLabel16.setFont(new java.awt.Font("Trebuchet MS", 0, 11)); // NOI18N
        jLabel16.setText("Gender :");

        lbl_Fname.setFont(new java.awt.Font("Trebuchet MS", 0, 11)); // NOI18N

        lbl_sex.setFont(new java.awt.Font("Trebuchet MS", 0, 11)); // NOI18N

        lbl_Fphone.setFont(new java.awt.Font("Trebuchet MS", 0, 11)); // NOI18N

        lbl_Faddress.setFont(new java.awt.Font("Trebuchet MS", 0, 11)); // NOI18N

        jLabel5.setFont(new java.awt.Font("Trebuchet MS", 0, 11)); // NOI18N
        jLabel5.setText("Phone No.");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4)))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel15)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(lbl_Fid, javax.swing.GroupLayout.DEFAULT_SIZE, 99, Short.MAX_VALUE)
                    .addComponent(lbl_age, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lbl_Fname, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(5, 5, 5)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel16)
                    .addComponent(jLabel5)
                    .addComponent(jLabel6))
                .addGap(14, 14, 14)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lbl_Fphone, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbl_Faddress, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbl_sex, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(22, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addComponent(lbl_Fid, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(1, 1, 1))
                    .addComponent(jLabel16)
                    .addComponent(lbl_sex, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(10, 10, 10)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel5, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lbl_Fphone, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lbl_Fname, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(10, 10, 10)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(jLabel6)
                        .addComponent(lbl_Faddress, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jLabel15)
                        .addComponent(lbl_age, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(20, 20, 20))
        );

        jDateChooser1.setDate(new Date());
        jDateChooser1.setDateFormatString("dd-MM-yyyy");
        jDateChooser1.setFont(new java.awt.Font("Trebuchet MS", 0, 11)); // NOI18N
        jDateChooser1.setOpaque(false);
        jDateChooser1.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                jDateChooser1PropertyChange(evt);
            }
        });

        jLabel17.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(255, 0, 51));
        jLabel17.setText("0.00");

        jLabel18.setFont(new java.awt.Font("Trebuchet MS", 1, 12)); // NOI18N
        jLabel18.setForeground(new java.awt.Color(51, 51, 255));
        jLabel18.setText("Total (ltrs):");

        jCheckBox1.setFont(new java.awt.Font("Trebuchet MS", 0, 11)); // NOI18N
        jCheckBox1.setSelected(true);
        jCheckBox1.setText("Display All Collection");
        jCheckBox1.setOpaque(false);
        jCheckBox1.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                jCheckBox1ItemStateChanged(evt);
            }
        });

        jButton3.setFont(new java.awt.Font("Segoe UI", 0, 10)); // NOI18N
        jButton3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/arrow_left.gif"))); // NOI18N
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jComboBox1.setFont(new java.awt.Font("Trebuchet MS", 0, 11)); // NOI18N
        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jComboBox1.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                jComboBox1ItemStateChanged(evt);
            }
        });

        jButton4.setFont(new java.awt.Font("Segoe UI", 0, 10)); // NOI18N
        jButton4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/arrow_right.gif"))); // NOI18N
        jButton4.setHorizontalTextPosition(javax.swing.SwingConstants.LEADING);
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        jButton5.setText("Populate");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jCheckBox1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(3, 3, 3)
                                .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(3, 3, 3)
                                .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jScrollPane1)
                            .addComponent(jSeparator1)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jButton5))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel1)
                                    .addComponent(jLabel2))
                                .addGap(4, 4, 4)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(6, 6, 6)
                                        .addComponent(jButton1)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addContainerGap())
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(3, 3, 3)
                                .addComponent(jLabel12)
                                .addGap(7, 7, 7))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel7)
                                .addGap(18, 18, 18)))
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(txtwater, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtquantity, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(10, 10, 10)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel13)
                            .addComponent(jLabel8))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtsnf, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cmbSession, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(10, 10, 10)
                                .addComponent(jLabel14)
                                .addGap(25, 25, 25))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel9)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)))
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jDateChooser1, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(80, 80, 80))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(txtprotein, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(10, 10, 10)
                                .addComponent(jLabel10)
                                .addGap(9, 9, 9)
                                .addComponent(txtfat, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 8, Short.MAX_VALUE)
                                .addComponent(jLabel11)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)))
                        .addComponent(txtfp, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 74, Short.MAX_VALUE)
                        .addComponent(jLabel18)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel17)
                        .addGap(23, 23, 23))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(9, 9, 9)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jLabel2))
                                    .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(56, 56, 56))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(11, 11, 11)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 1, Short.MAX_VALUE)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 2, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(12, 12, 12)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtwater, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel8)
                            .addComponent(jLabel7))
                        .addComponent(txtsnf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtprotein, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel9))
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtfat, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel10))
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtfp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel11)))
                    .addComponent(jLabel17, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel18, javax.swing.GroupLayout.Alignment.TRAILING))
                .addGap(12, 12, 12)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jDateChooser1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel14, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(cmbSession, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel13, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel12, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(txtquantity, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton5))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 248, Short.MAX_VALUE)
                .addGap(5, 5, 5)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jButton4, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addComponent(jButton3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addComponent(jComboBox1, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jCheckBox1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(11, 11, 11))
        );

        jPanel1Layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {jButton1, jTextField2});

        getContentPane().add(jPanel1, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void getRate () {                 
       int i=0;
       String avail="0.0";
       org.hibernate.Session session = HibernateUtil.getSessionFactory().openSession();
      try {        
           
           session.beginTransaction();
           Query q = session.createQuery("SELECT con.saleRate from DtConstants con");
           List auth=q.list();
           Iterator iterator=auth.iterator();
           if(iterator.hasNext()){ 
                   Object stock=(Object)auth.get(0);
                   rate=Double.parseDouble(sup.getCostValue(stock));
           }
           session.getTransaction().commit();
         }catch (HibernateException he) {
                 errorFields = new JLabel("<HTML><FONT COLOR = Blue>'"+he.getMessage()+"'</FONT></HTML>");
                 JOptionPane.showMessageDialog(null,errorFields,"DMS",JOptionPane.ERROR_MESSAGE);

         }finally {
             session.close(); 
         }
    }
   
    
    public void getUserId(String userid){
        this.userid=userid;
        getRate ();
        month_begin=sup.sqlDate(dt.seekMonth_Begin(jDateChooser1.getDate()));
    }
    private void jTextField1KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField1KeyReleased
        // TODO add your handling code here:
        resetFields();
        month_begin=sup.sqlDate(dt.seekMonth_Begin(jDateChooser1.getDate()));
        String date=new SimpleDateFormat("dd-MM-yyyy").format( jDateChooser1.getDate());
        String date1=date.substring(3,date.length());
        panel_Search search=new panel_Search();
        search.formload();
        int option=JOptionPane.showConfirmDialog(null,search, "Farmer Search",JOptionPane.OK_CANCEL_OPTION,JOptionPane.PLAIN_MESSAGE);
        if(option==JOptionPane.OK_OPTION){
            String farmerid=search.getPatientId();
            if(!farmerid.equals("")){
                 id=0;
                 jCheckBox1.setSelected(false);
                 fillFields(farmer.FarmerID_Search(farmerid));                  
                 collec_display(1,farmerid,month_begin,sup.sqlDate(date),0);
                 jTable1.setModel(farmer_model);
                 SwingUtilities.invokeLater(new Runnable() {
                    public void run() {
                    jTable1.getColumnModel().getColumn(7).setCellRenderer( new  labelRenderer());
                    jTable1.getColumnModel().getColumn(8).setCellRenderer( new  labelRenderer());
                    ColumnResizer.adjustColumnPreferredWidths (jTable1);
                    jTable1.revalidate();
                 }});
             jLabel17.setText(String.valueOf(total));
            }
           
        }
        jTextField2.setText("Type here");
                           
    }//GEN-LAST:event_jTextField1KeyReleased

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        String farmerid=lbl_Fid.getText();
        month_begin=sup.sqlDate(dt.seekMonth_Begin(jDateChooser1.getDate()));
        String date1=new SimpleDateFormat("dd-MM-yyyy").format( new Date());
//        String date2=date1.substring(3,date1.length());
        if(!farmerid.equals("")){
             String date=new SimpleDateFormat("dd-MM-yyyy").format(jDateChooser1.getDate());
             String farmerId=farmerid;
             month_begin=sup.sqlDate(dt.seekMonth_Begin(jDateChooser1.getDate()));
             double quantity=Double.parseDouble(new superCls().getCostValue(txtquantity.getText()));
             double water=Double.parseDouble(new superCls().getCostValue(txtwater.getText()));
             double snf=Double.parseDouble(new superCls().getCostValue(txtsnf.getText()));
             double proteins=Double.parseDouble(new superCls().getCostValue(txtprotein.getText()));
             double fat=Double.parseDouble(new superCls().getCostValue(txtfat.getText()));
             double fp=Double.parseDouble(new superCls().getCostValue(txtfp.getText()));
             double debit=quantity*rate;
             double credit=0.0;
             String desc="Milk";
             String dept_id="01";
             
             String session1=new superCls().getValue(cmbSession.getSelectedItem());
             String attendant=userid;
             int idno=Integer.parseInt(new superCls().getIntValue(farmerid));
             if(!farmerid.equals("")&& quantity!=0.0){
                 quantity=quantity;
                 if(this.DailyCollection(id, date, farmerId, quantity, water, snf, proteins, fat, fp, session1, attendant,rate, stock_id, "in_collection", idno, pid, desc,debit,dept_id)){  
                   collec_display(1,farmerid,month_begin,sup.sqlDate(date),0);
                   jTable1.setModel(farmer_model);
                   SwingUtilities.invokeLater(new Runnable() {
                        public void run() {
                            jTable1.getColumnModel().getColumn(7).setCellRenderer( new  labelRenderer());
                            jTable1.getColumnModel().getColumn(8).setCellRenderer( new  labelRenderer());
                            ColumnResizer.adjustColumnPreferredWidths (jTable1);
                            jTable1.revalidate();
                        }
                   });
                     id=0;
                     stock_id=0;
                     pid=0;
                     jLabel17.setText(sum_total(farmerid,month_begin,sup.sqlDate(date)));
                 }
             }else{
                 errorFields = new JLabel("<HTML><FONT COLOR = BLUE>Please make sure a farmer is selected and quantity is entered coreectly</FONT></HTML>");
                 JOptionPane.showMessageDialog(null,errorFields,"DMS",JOptionPane.ERROR_MESSAGE); 
             }
        }
    }//GEN-LAST:event_jButton2ActionPerformed

    
    private boolean collection_delete(int id,int stockid,int pid){
       org.hibernate.Session session = HibernateUtil.getSessionFactory().openSession();
       Transaction tx = null;
       boolean status=false;
      try{
         tx = session.beginTransaction();
         DtDailycollection collec = (DtDailycollection)session.get(DtDailycollection.class, id);   
         DtMstock stock = (DtMstock)session.get(DtMstock.class, stockid); 
         DtPurchasesAccount p_account = (DtPurchasesAccount)session.get(DtPurchasesAccount.class, pid); 
         if(collec!=null)
             session.delete(collec); 
         if(stock!=null)
            session.delete(p_account);
         if(p_account!=null)
            session.delete(stock);   
         tx.commit();
         status=true;
      }catch (HibernateException e) {
         if (tx!=null) tx.rollback();
             errorFields = new JLabel("<HTML><FONT COLOR = BLUE>'"+e.getMessage()+"'</FONT></HTML>");
             JOptionPane.showMessageDialog(null,errorFields,"DMS",JOptionPane.ERROR_MESSAGE); 
      }finally {
         session.close(); 
      }
     return status;
   }
    
    
    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        resetFields();
        jCheckBox1.setSelected(false);
        String farmerid=jTextField2.getText();
        String date=new SimpleDateFormat("dd-MM-yyyy").format( new Date());
        String date1=date.substring(3,date.length());
        if(!farmerid.equals("")){
            id=0;
           fillFields(farmer.FarmerID_Search(farmerid));                  
           collec_display(1,farmerid,month_begin,sup.sqlDate(date),0);
           jTable1.setModel(farmer_model);
           SwingUtilities.invokeLater(new Runnable() {
                    public void run() {
                    jTable1.getColumnModel().getColumn(7).setCellRenderer( new  labelRenderer());
                    jTable1.getColumnModel().getColumn(8).setCellRenderer( new  labelRenderer());
                    ColumnResizer.adjustColumnPreferredWidths (jTable1);
                    jTable1.revalidate();
                 }});
           jLabel17.setText(sup.doubleFormatter(sum_total(farmerid,month_begin,sup.sqlDate(date))));
//           jLabel17.setText(String.valueOf(total));
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void txtquantityFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtquantityFocusGained
        // TODO add your handling code here:
        txtquantity.selectAll();
    }//GEN-LAST:event_txtquantityFocusGained

    private void txtwaterFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtwaterFocusGained
        // TODO add your handling code here:
        txtwater.selectAll();
    }//GEN-LAST:event_txtwaterFocusGained

    private void txtsnfFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtsnfFocusGained
        // TODO add your handling code here:
        txtsnf.selectAll();
    }//GEN-LAST:event_txtsnfFocusGained

    private void txtproteinFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtproteinFocusGained
        // TODO add your handling code here:
        txtprotein.selectAll();
    }//GEN-LAST:event_txtproteinFocusGained

    private void txtfatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtfatActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtfatActionPerformed

    private void txtfatFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtfatFocusGained
        // TODO add your handling code here:
        txtfat.selectAll();
    }//GEN-LAST:event_txtfatFocusGained

    private void txtfpFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtfpFocusGained
        // TODO add your handling code here:
        txtfp.selectAll();
    }//GEN-LAST:event_txtfpFocusGained

    private void jTextField2FocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextField2FocusGained
        // TODO add your handling code here:
        jTextField2.selectAll();
    }//GEN-LAST:event_jTextField2FocusGained

    public Object[] getStock_details(int id){
        org.hibernate.Session session = HibernateUtil.getSessionFactory().openSession();
        Object[] idx=new Object[2];
      try {        
           session.beginTransaction();
           Query q = session.createQuery("SELECT stck.id, pur.id from DtDailycollection collec INNER JOIN collec.stock stck INNER JOIN collec.purchases pur WHERE collec.id=:id");
           q.setParameter("id", id);
           List auth=q.list();
           for(Object o:auth){
               idx=(Object[])o;    
           }
           session.getTransaction().commit();
         }catch (HibernateException he) {
                 errorFields = new JLabel("<HTML><FONT COLOR = Blue>'"+he.getStackTrace()+"'</FONT></HTML>");
                 JOptionPane.showMessageDialog(null,errorFields,"DMS",JOptionPane.ERROR_MESSAGE);

         }finally {
             session.close(); 
         }
      return idx;
    }
    
    
    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked
        // TODO add your handling code here:
        int col=jTable1.getSelectedColumn();
        int row=jTable1.getSelectedRow();
        String date=new SimpleDateFormat("dd-MM-yyyy").format(jDateChooser1.getDate());    
        String date1=sup.getValue(jTable1.getValueAt(row, 3));         
        String farmerid=sup.getValue(jTable1.getValueAt(row, 1)); 
        double qty=Double.parseDouble(sup.getCostValue(jTable1.getValueAt(row, 5)));
        id=Integer.parseInt(sup.getIntValue(jTable1.getValueAt(row, 0)));     
        if(col==7){
            jCheckBox1.setSelected(false);
            txtquantity.setText(sup.getCostValue(qty));
            cmbSession.setSelectedItem(sup.getValue(jTable1.getValueAt(row, 4)));
            jDateChooser1.setDate(sup.StringToJDate(sup.getValue(jTable1.getValueAt(row, 3))));
            stock_id=Integer.parseInt(sup.getIntValue(getStock_details(id)[0]));
            pid=Integer.parseInt(sup.getIntValue(getStock_details(id)[1]));
            fillFields(farmer.FarmerID_Search(farmerid)); 
        }
        if(col==8){  
            int  result = JOptionPane.showConfirmDialog(this,"Are you sure you want Delete This Record!","Dairy Management System",JOptionPane.OK_CANCEL_OPTION, JOptionPane.WARNING_MESSAGE );
            if(result==JOptionPane.OK_OPTION){
                stock_id=Integer.parseInt(sup.getIntValue(getStock_details(id)[0]));
                pid=Integer.parseInt(sup.getIntValue(getStock_details(id)[1]));
                if(collection_delete(id,stock_id,pid)){
                    DefaultTableModel model=(DefaultTableModel)jTable1.getModel();
                    model.removeRow(row);
                    errorFields = new JLabel("<HTML><FONT COLOR = Blue>Record Deleted successfully</FONT></HTML>");
                    JOptionPane.showMessageDialog(null,errorFields,"DMS",JOptionPane.INFORMATION_MESSAGE);
//                    collec_display(1,farmerid,month_begin,sup.sqlDate(date),0);
//                    jTable1.setModel(farmer_model);
//                    SwingUtilities.invokeLater(new Runnable() {
//                    @Override
//                    public void run() {
//                        jTable1.getColumnModel().getColumn(7).setCellRenderer( new  labelRenderer());
//                        jTable1.getColumnModel().getColumn(8).setCellRenderer( new  labelRenderer());
//                        ColumnResizer.adjustColumnPreferredWidths (jTable1);
//                        jTable1.revalidate();
//                  }});
                }   
            }
            jLabel17.setText(sup.doubleFormatter(total));
        }
    }//GEN-LAST:event_jTable1MouseClicked

    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField1ActionPerformed

    private void jDateChooser1PropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_jDateChooser1PropertyChange
        // TODO add your handling code here:
        if(evt.getSource()==jDateChooser1){
            int col=jTable1.getSelectedColumn();
            
        }
    }//GEN-LAST:event_jDateChooser1PropertyChange

    private void jTextField1FocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextField1FocusGained
        // TODO add your handling code here:
        jTextField1.selectAll();
    }//GEN-LAST:event_jTextField1FocusGained

    private void jCheckBox1ItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_jCheckBox1ItemStateChanged
        // TODO add your handling code here:
        if(jCheckBox1.isSelected()){
            id=0;
            resetFields();
            String date=new SimpleDateFormat("dd-MM-yyyy").format(jDateChooser1.getDate()); 
            month_begin=sup.sqlDate(dt.seekMonth_Begin(jDateChooser1.getDate()));
            collec_display(0,"",month_begin,sup.sqlDate(date),0);
            jTable1.setModel(farmer_model);
            SwingUtilities.invokeLater(new Runnable() {
            public void run() {
                jTable1.getColumnModel().getColumn(7).setCellRenderer( new  labelRenderer());
                jTable1.getColumnModel().getColumn(8).setCellRenderer( new  labelRenderer());
                ColumnResizer.adjustColumnPreferredWidths (jTable1);
                jTable1.revalidate();
          }});
            
             lbl_Fid.setText("N/A");
             lbl_Fname.setText("All");
        }
    }//GEN-LAST:event_jCheckBox1ItemStateChanged

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        int value=Integer.parseInt(new superCls().getIntValue(jComboBox1.getSelectedIndex()));
        int max=jComboBox1.getItemCount();
        int upperlimit=30;
        if(value!=0){
            value--;
            jComboBox1.setSelectedItem(value);
        }else{
        }
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jComboBox1ItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_jComboBox1ItemStateChanged
        // TODO add your handling code here:
        String fid=lbl_Fid.getText();
        int value=Integer.parseInt(new superCls().getIntValue(jComboBox1.getSelectedItem())),upperlimit=30;
        if(value>0)
          upperlimit=(value)*upperlimit;
        else
         upperlimit=0;
        
        String date=new SimpleDateFormat("dd-MM-yyyy").format(jDateChooser1.getDate()); 
            month_begin=sup.sqlDate(dt.seekMonth_Begin(jDateChooser1.getDate()));            
        if(fid==null||fid.equals("N/A")||fid.equals(""))
           collec_display(0,"",month_begin,sup.sqlDate(date),upperlimit);
        else
           collec_display(1,fid,month_begin,sup.sqlDate(date),upperlimit);
        jTable1.setModel(farmer_model);
        SwingUtilities.invokeLater(new Runnable() {
            public void run() {
                jTable1.getColumnModel().getColumn(7).setCellRenderer( new  labelRenderer());
                ColumnResizer.adjustColumnPreferredWidths (jTable1);
                jTable1.revalidate();
            }});
    }//GEN-LAST:event_jComboBox1ItemStateChanged

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
        int value=Integer.parseInt(new superCls().getIntValue(jComboBox1.getSelectedIndex()));
        int max=jComboBox1.getItemCount();
        int upperlimit=30;
        if(value!=max){
            value++;
            jComboBox1.setSelectedItem(value);
        }else{
        }
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        // TODO add your handling code here:
        String date=new SimpleDateFormat("dd-MM-yyyy").format(jDateChooser1.getDate()); 
            month_begin=sup.sqlDate(dt.seekMonth_Begin(jDateChooser1.getDate()));
            String farmerid=lbl_Fid.getText();
            int col=jTable1.getSelectedColumn();
            if(farmerid!=null && !farmerid.equals("") && col!=7){
                collec_display(1,farmerid,month_begin,sup.sqlDate(date),0);
                jLabel17.setText(sup.doubleFormatter(sum_total(farmerid,month_begin,sup.sqlDate(date))));
            }
            else 
                collec_display(0,"",month_begin,sup.sqlDate(date),0);

            jTable1.setModel(farmer_model);
            SwingUtilities.invokeLater(new Runnable() {
            public void run() {
                jTable1.getColumnModel().getColumn(7).setCellRenderer( new  labelRenderer());
                jTable1.getColumnModel().getColumn(8).setCellRenderer( new  labelRenderer());
                ColumnResizer.adjustColumnPreferredWidths (jTable1);
                jTable1.revalidate();
          }});
    }//GEN-LAST:event_jButton5ActionPerformed

    public void fillFields(DtFarmerdetails details){
       lbl_Fid.setText(details.getFarmerId());
       lbl_Faddress.setText(details.getPaddress());
       lbl_Fname.setText(details.getFname()+" "+details.getLname());
       lbl_Fphone.setText(details.getPphone());
       lbl_age.setText(String.valueOf(new superCls().getDateDiff(new superCls().StringToDate(details.getDob()),new Date(),"YEARS")));
       lbl_sex.setText(details.getGender());        
    }
    
    public void resetFields(){
       lbl_Fid.setText("");
       lbl_Faddress.setText("");
       lbl_Fname.setText("");
       lbl_Fphone.setText("");
       lbl_age.setText("");
       lbl_sex.setText(""); 
       txtquantity.setText("0.00");
    }
    
   public void formload(){
       resetFields();
       jComboBox1.setModel(new superCls().pagination("DtDailycollection"));
       String date=new SimpleDateFormat("dd-MM-yyyy").format( new Date());
//       String date1=date.substring(3,date.length());
       month_begin=sup.sqlDate(dt.seekMonth_Begin(jDateChooser1.getDate()));
       collec_display(0,"",month_begin,sup.sqlDate(date),0);
       jTable1.setModel(farmer_model);
       SwingUtilities.invokeLater(new Runnable() {
                    public void run() {
                    jTable1.getColumnModel().getColumn(7).setCellRenderer( new  labelRenderer());
                    jTable1.getColumnModel().getColumn(8).setCellRenderer( new  labelRenderer());
                    ColumnResizer.adjustColumnPreferredWidths (jTable1);
                    jTable1.revalidate();
                 }});
       jLabel17.setText(sup.doubleFormatter(total));
   } 
    
    public boolean DailyCollection(int id,String date, String farmerId, double quantity, double water, double snf, double proteins, double fat, double fp, String session1, String attendant,double rate,int stock_id, String descriprion, int companyId,int purchase_id, String desc,double debit,String dept_id){
      Session session = HibernateUtil.getSessionFactory().openSession();
      Transaction tx = null;
      boolean state=false;
      try{
         tx = session.beginTransaction();
         DtDailycollection collection=new DtDailycollection(id, sup.sqlDate(date), farmerId, quantity, water, snf, proteins, fat, fp, session1, attendant,rate);
         DtMstock stock=new DtMstock(stock_id, sup.sqlDate(date), descriprion, companyId, quantity, 0.0, attendant);
         DtPurchasesAccount p_account=new DtPurchasesAccount(purchase_id,sup.sqlDate(date), dept_id, desc, debit, 0.00, quantity,farmerId);
         if(stock_id!=0 && id!=0){
            session.saveOrUpdate(stock);
            session.saveOrUpdate(p_account);
            collection.setStock(stock);
            collection.setPurchases(p_account);
            session.saveOrUpdate(collection);
         }
         else{
             session.save(stock);
             session.save(p_account);
             collection.setStock(stock);
             collection.setPurchases(p_account);
             session.save(collection);
         }
            //save collection
        
         
         tx.commit();
         state=true;         
      }catch (HibernateException e) {
         if (tx!=null) tx.rollback();
             errorFields = new JLabel("<HTML><FONT COLOR = BLUE>'"+e.getMessage()+"'</FONT></HTML>");
             JOptionPane.showMessageDialog(null,errorFields,"DMS",JOptionPane.INFORMATION_MESSAGE);
      }finally {
         session.close(); 
      }
      return state;
   }
    
    public void collec_display(int val,String fid,Date date1,Date date2,int upperlimit) {
    try {
        String hql;
        Session session = HibernateUtil.getSessionFactory().openSession();
        session.beginTransaction();
        switch(val){
            case 0:
                hql="from DtDailycollection c WHERE c.date between :date1 and :date2 order by c.id DESC";
                break;                          
            case 1:
                hql="from DtDailycollection c WHERE c.farmerId=:id AND c.date between :date1 and :date2 order by c.id DESC";
                break;
            case 2:
                hql="from DtDailycollection c WHERE c.farmerId=:id AND c.date between :date1 and :date2 order by c.id DESC";
                break;    
            default:
                hql="from DtDailycollection c WHERE c.date between :date1 and :date2 order by c.id desc";
                break;        
    }
        Query q = session.createQuery(hql);
        q.setDate("date1", date1);
        q.setDate("date2", date2);        
        if(val==1)
            q.setParameter("id", fid);
        q.setFirstResult(upperlimit);
        q.setMaxResults(30);
        List resultList = q.list();
        displayResult(resultList);
        session.getTransaction().commit();
    } catch (HibernateException he) {
        he.printStackTrace();
    }
}
    
    private void displayResult(List resultList) {
    Vector tableData = new Vector();
    total=0.0;
    String header[]={"Record","id","Name","Date","Session","Quantity","Attendant","",""};
    Vector<String> tableHeaders= new Vector<>();
    tableHeaders.addAll(Arrays.asList(header));
    for(Object o : resultList) {
        
        DtDailycollection collection = (DtDailycollection)o;
        Vector<Object> oneRow = new Vector<>();
        List col=Arrays.asList(collection.getId(),
                               collection.getFarmerId(),
                               sup.Farmer_name(collection.getFarmerId()),
                               collection.getDate(),
                               collection.getSession(),
                               collection.getQuantity(),
                               collection.getAttendant(),
                               "edit",
                               "delete");
        total+=collection.getQuantity();
        oneRow.addAll(col);
        tableData.add(oneRow);
    }
    if(resultList.isEmpty()){
       farmer_model=new DefaultTableModel(new String[20][9],header);   
    }else{
        farmer_model=new DefaultTableModel(tableData, tableHeaders);
        jLabel17.setText(sup.doubleFormatter(total));
    }
}
    
    private String sum_total (String id,Date date1, Date date2) {                 
       int i=0;
       double total=0.0;
       DefaultComboBoxModel tmodel =new DefaultComboBoxModel();
       org.hibernate.Session session = HibernateUtil.getSessionFactory().openSession();
      try {        
           session.beginTransaction();
           Query q = session.createQuery("SELECT sum(c.quantity) from DtDailycollection c WHERE c.farmerId=:id AND c.date between :date1 and :date2 order by c.id DESC");
           q.setParameter("id", id);
           q.setParameter("date1", date1);
           q.setParameter("date2", date2);
           List auth=q.list();
           Iterator iterator=auth.iterator();
           if(iterator.hasNext()){  
               total=(double)iterator.next();
                       
           }
           session.getTransaction().commit();
         }catch (HibernateException he) {
                 errorFields = new JLabel("<HTML><FONT COLOR = Blue>'"+he.getMessage()+"'</FONT></HTML>");
                 JOptionPane.showMessageDialog(null,errorFields,"DMS",JOptionPane.ERROR_MESSAGE);

         }finally {
             session.close(); 
         }
          return String.valueOf(total);
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox cmbSession;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JCheckBox jCheckBox1;
    private javax.swing.JComboBox jComboBox1;
    private com.toedter.calendar.JDateChooser jDateChooser1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JLabel lbl_Faddress;
    private javax.swing.JLabel lbl_Fid;
    private javax.swing.JLabel lbl_Fname;
    private javax.swing.JLabel lbl_Fphone;
    private javax.swing.JLabel lbl_age;
    private javax.swing.JLabel lbl_sex;
    private javax.swing.JTextField txtfat;
    private javax.swing.JTextField txtfp;
    private javax.swing.JTextField txtprotein;
    private javax.swing.JTextField txtquantity;
    private javax.swing.JTextField txtsnf;
    private javax.swing.JTextField txtwater;
    // End of variables declaration//GEN-END:variables
}
