/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ui;

import classes.superCls;
import farmTech.util.HibernateUtil;
import custom_jPanels.SimpleGradientPanel;
import farm.entity.DtOrders;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.Iterator;
import java.util.List;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import org.hibernate.HibernateException;
import org.hibernate.Query;
import org.hibernate.Session;
import org.hibernate.Transaction;

/**
 *
 * @author Kent
 */
public class OrderEdit extends javax.swing.JPanel {
 superCls sup=new superCls();
 private String orderno;
    /**
     * Creates new form OrderEdit
     */
    public OrderEdit() {
        initComponents();
    }
    
    public void formload(String orderno){
        this.orderno=orderno;
        if(!orderno.equals("")){
            this.FindOrder(orderno);
            cmbstate.setSelectedIndex(-1);
        }        
    }

    
    public void FindOrder(String orderNo){
       org.hibernate.Session session = HibernateUtil.getSessionFactory().openSession();
       Transaction tx = null;
       String suppliername="UNDEFINED";
      try{
         Query q = session.getNamedQuery("DtOrders.findByOrderNo");
         q.setParameter("orderNo", orderNo);
         q.setCacheable(true);
         List<DtOrders> orders=q.list();           
         Iterator<DtOrders> itr=orders.iterator(); 
         if(itr.hasNext()){
             DtOrders ord=(DtOrders)itr.next();
             lbl_supplier.setText(sup.FindSupplierName(ord.getSupplierid()));
             lbl_order.setText(ord.getOrderNo());
             lbl_date.setText(String.valueOf(ord.getDate()));
             cmbstate.setSelectedItem(ord.getState());
            }
      }catch (HibernateException e) {
         if (tx!=null) tx.rollback();
             JLabel errorFields = new JLabel("<HTML><FONT COLOR = BLUE>'"+e.getMessage()+"'</FONT></HTML>");
             JOptionPane.showMessageDialog(null,errorFields,"farmTech",JOptionPane.ERROR_MESSAGE); 
      }finally {
         session.close(); 
      }
   }
    
    public boolean updateOrderState(String state,String orderNo){
      Session session = HibernateUtil.getSessionFactory().openSession();      
      Transaction tx = null;
      boolean status=false;
      DtOrders orders;
      try{   tx=session.beginTransaction();
            Query q = session.getNamedQuery("DtOrders.findByOrderNo");
            q.setParameter("orderNo", orderNo);
            List<DtOrders> order=q.list();           
            Iterator<DtOrders> itr=order.iterator();             
         if(itr.hasNext()){
              orders=(DtOrders)itr.next();
              orders.setStateDate(sup.sqlDate(new SimpleDateFormat("dd-MM-yyyy").format(new Date())));
              orders.setState(state);
              session.update(orders);  
            }
         tx.commit();
          status=true;
            
      }catch (HibernateException e) {
         if (tx!=null) tx.rollback();
      }finally {
         session.flush();
         session.close(); 
      }
      return status;
   }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new SimpleGradientPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        lbl_supplier = new javax.swing.JLabel();
        lbl_order = new javax.swing.JLabel();
        lbl_date = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        cmbstate = new javax.swing.JComboBox();
        jButton1 = new javax.swing.JButton();

        setLayout(new java.awt.BorderLayout());

        jLabel1.setFont(new java.awt.Font("Segoe UI Semibold", 0, 10)); // NOI18N
        jLabel1.setText("Supplier Name :");

        jLabel2.setFont(new java.awt.Font("Segoe UI Semibold", 0, 10)); // NOI18N
        jLabel2.setText("Order No :");

        jLabel3.setFont(new java.awt.Font("Segoe UI Semibold", 0, 10)); // NOI18N
        jLabel3.setText("Issue Date :");

        jLabel4.setText("Order Status Change ");

        lbl_supplier.setFont(new java.awt.Font("Segoe UI Semibold", 0, 10)); // NOI18N
        lbl_supplier.setToolTipText("");

        lbl_order.setFont(new java.awt.Font("Segoe UI Semibold", 0, 10)); // NOI18N
        lbl_order.setToolTipText("");

        lbl_date.setFont(new java.awt.Font("Segoe UI Semibold", 0, 10)); // NOI18N
        lbl_date.setToolTipText("");

        jLabel8.setFont(new java.awt.Font("Segoe UI Semibold", 0, 10)); // NOI18N
        jLabel8.setText("Status :");

        cmbstate.setFont(new java.awt.Font("Segoe UI Semibold", 0, 10)); // NOI18N
        cmbstate.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "UNFULFILLED", "FULFILLED", "CANCELLED" }));
        cmbstate.setSelectedIndex(-1);
        cmbstate.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cmbstateItemStateChanged(evt);
            }
        });

        jButton1.setText("Update");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel1)
                                    .addComponent(jLabel2)
                                    .addComponent(jLabel3))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(lbl_supplier, javax.swing.GroupLayout.DEFAULT_SIZE, 235, Short.MAX_VALUE)
                                    .addComponent(lbl_order, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(lbl_date, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel8)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(cmbstate, javax.swing.GroupLayout.PREFERRED_SIZE, 240, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(114, 114, 114)
                        .addComponent(jButton1)))
                .addContainerGap(24, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(jLabel4)
                .addGap(3, 3, 3)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lbl_supplier, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lbl_order, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lbl_date, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(35, 35, 35)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel8)
                    .addComponent(cmbstate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButton1)
                .addContainerGap(32, Short.MAX_VALUE))
        );

        add(jPanel1, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents

    private void cmbstateItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cmbstateItemStateChanged
        // TODO add your handling code here:
        
    }//GEN-LAST:event_cmbstateItemStateChanged

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        String state=sup.getValue(cmbstate.getSelectedItem());
        if(!state.equals("") && !orderno.equals("")){
            this.updateOrderState(state, orderno);
            JLabel errorFields = new JLabel("<HTML><FONT COLOR = BLUE>Update successfull</FONT></HTML>");
            JOptionPane.showMessageDialog(null,errorFields,"farmTech",JOptionPane.INFORMATION_MESSAGE); 
        }else{
            JLabel errorFields = new JLabel("<HTML><FONT COLOR = BLUE>Please make sure orderNo is valid and state is selected</FONT></HTML>");
             JOptionPane.showMessageDialog(null,errorFields,"farmTech",JOptionPane.ERROR_MESSAGE); 
        }
    }//GEN-LAST:event_jButton1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox cmbstate;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JLabel lbl_date;
    private javax.swing.JLabel lbl_order;
    private javax.swing.JLabel lbl_supplier;
    // End of variables declaration//GEN-END:variables
}
