/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * signup.java
 *
 * Created on Dec 3, 2013, 9:21:25 PM
 */

package ui;

import classes.superCls;
import custom_jPanels.RoundRectGradientPanel;
import farm.entity.DtUserprivileges;
import farm.entity.DtUsers;
import farmTech.util.HibernateUtil;
import java.text.SimpleDateFormat;
import java.util.Date;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import org.hibernate.HibernateException;
import org.hibernate.Transaction;
import org.hibernate.Session;

/**
 *
 * @author KENT
 */
public class signup extends javax.swing.JInternalFrame {

    /** Creates new form signup */
    DtUsers detail;
    String state="false";
    public signup() {
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new RoundRectGradientPanel();
        jLabel80 = new javax.swing.JLabel();
        jLabel82 = new javax.swing.JLabel();
        jLabel84 = new javax.swing.JLabel();
        jLabel86 = new javax.swing.JLabel();
        txtUphone = new javax.swing.JTextField();
        jLabel85 = new javax.swing.JLabel();
        jLabel87 = new javax.swing.JLabel();
        txtUfname = new javax.swing.JTextField();
        txtUaddress = new javax.swing.JTextField();
        jLabel83 = new javax.swing.JLabel();
        txtUlname = new javax.swing.JTextField();
        txtUsername = new javax.swing.JTextField();
        txtUIdno = new javax.swing.JTextField();
        jLabel88 = new javax.swing.JLabel();
        txtUResidence = new javax.swing.JTextField();
        jLabel99 = new javax.swing.JLabel();
        jLabel100 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jPasswordField1 = new javax.swing.JPasswordField();
        jPasswordField2 = new javax.swing.JPasswordField();
        jButton1 = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox();
        jDateChooser1 = new com.toedter.calendar.JDateChooser();
        jLabel4 = new javax.swing.JLabel();
        jComboBox2 = new javax.swing.JComboBox();

        setClosable(true);
        setDefaultCloseOperation(javax.swing.WindowConstants.HIDE_ON_CLOSE);
        setIconifiable(true);
        setTitle("Create a new account");
        setDoubleBuffered(true);
        setFrameIcon(new javax.swing.ImageIcon(getClass().getResource("/images/ox-cow.png"))); // NOI18N
        setOpaque(true);
        setVerifyInputWhenFocusTarget(false);
        setVisible(true);

        jPanel1.setOpaque(false);

        jLabel80.setText("First Name:");
        jLabel80.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);

        jLabel82.setText("Last Name :");

        jLabel84.setText("Telephone No. :");

        jLabel86.setText("Email :");

        txtUphone.setBorder(null);

        jLabel85.setText("Adrress :");

        jLabel87.setText("DOB :");

        txtUfname.setBorder(null);

        txtUaddress.setBorder(null);

        jLabel83.setText("Identification No :");

        txtUlname.setBorder(null);

        txtUsername.setBorder(null);

        txtUIdno.setBorder(null);

        jLabel88.setText("User Name :");

        txtUResidence.setBorder(null);

        jLabel99.setForeground(new java.awt.Color(255, 0, 51));
        jLabel99.setText("*");

        jLabel100.setForeground(new java.awt.Color(255, 0, 51));
        jLabel100.setText("*");

        jLabel1.setText("Password :");

        jLabel2.setText("Confirm Password");

        jPasswordField2.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                jPasswordField2FocusLost(evt);
            }
        });

        jButton1.setText("Submit");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel3.setText("Sex :");

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Female", "Male" }));

        jDateChooser1.setDate(new Date());
        jDateChooser1.setDateFormatString("dd-MM-yyyy");

        jLabel4.setText("Speciality");
        jLabel4.setToolTipText("if Doctor please select Specialization");

        jComboBox2.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Administrator", "Farmer", "Collection", "Stores", "Reports" }));

        org.jdesktop.layout.GroupLayout jPanel1Layout = new org.jdesktop.layout.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jPanel1Layout.createSequentialGroup()
                .add(jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(jPanel1Layout.createSequentialGroup()
                        .add(30, 30, 30)
                        .add(jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                            .add(jLabel99)
                            .add(jLabel100))
                        .add(1, 1, 1)
                        .add(jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                            .add(jLabel3)
                            .add(jLabel83)
                            .add(jLabel82, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 93, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                            .add(jLabel80, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 81, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                            .add(jLabel84)
                            .add(jLabel85, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 81, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                            .add(jLabel86)
                            .add(jLabel87)
                            .add(jLabel88, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 93, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                            .add(jLabel1)
                            .add(jLabel2))
                        .add(jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                            .add(jPanel1Layout.createSequentialGroup()
                                .add(17, 17, 17)
                                .add(jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING, false)
                                    .add(txtUIdno, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 201, Short.MAX_VALUE)
                                    .add(txtUfname)
                                    .add(txtUlname)))
                            .add(jPanel1Layout.createSequentialGroup()
                                .add(18, 18, 18)
                                .add(jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING, false)
                                    .add(jDateChooser1, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 198, Short.MAX_VALUE)
                                    .add(txtUResidence)
                                    .add(txtUaddress)
                                    .add(txtUphone)
                                    .add(txtUsername)
                                    .add(jPasswordField1)
                                    .add(jPasswordField2)))
                            .add(jPanel1Layout.createSequentialGroup()
                                .add(16, 16, 16)
                                .add(jComboBox1, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                                .add(10, 10, 10)
                                .add(jLabel4)
                                .add(10, 10, 10)
                                .add(jComboBox2, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))))
                    .add(jPanel1Layout.createSequentialGroup()
                        .add(158, 158, 158)
                        .add(jButton1)))
                .add(30, 30, 30))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jPanel1Layout.createSequentialGroup()
                .add(30, 30, 30)
                .add(jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(jPanel1Layout.createSequentialGroup()
                        .add(6, 6, 6)
                        .add(jLabel99))
                    .add(jPanel1Layout.createSequentialGroup()
                        .add(5, 5, 5)
                        .add(jLabel80))
                    .add(txtUfname, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 20, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .add(6, 6, 6)
                .add(jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(jPanel1Layout.createSequentialGroup()
                        .add(5, 5, 5)
                        .add(jLabel82))
                    .add(txtUlname, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 20, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .add(6, 6, 6)
                .add(jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(jPanel1Layout.createSequentialGroup()
                        .add(6, 6, 6)
                        .add(jLabel100))
                    .add(jPanel1Layout.createSequentialGroup()
                        .add(5, 5, 5)
                        .add(jLabel83))
                    .add(txtUIdno, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 20, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .add(6, 6, 6)
                .add(jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(jComboBox1, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(jComboBox2, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(jPanel1Layout.createSequentialGroup()
                        .add(6, 6, 6)
                        .add(jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                            .add(jLabel3, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 15, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                            .add(jLabel4))))
                .add(6, 6, 6)
                .add(jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(jPanel1Layout.createSequentialGroup()
                        .add(5, 5, 5)
                        .add(jLabel84))
                    .add(txtUphone, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 20, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .add(6, 6, 6)
                .add(jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(jPanel1Layout.createSequentialGroup()
                        .add(5, 5, 5)
                        .add(jLabel85))
                    .add(txtUaddress, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 20, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .add(6, 6, 6)
                .add(jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(jPanel1Layout.createSequentialGroup()
                        .add(5, 5, 5)
                        .add(jLabel86))
                    .add(txtUResidence, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 20, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .add(6, 6, 6)
                .add(jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(jPanel1Layout.createSequentialGroup()
                        .add(5, 5, 5)
                        .add(jLabel87))
                    .add(jDateChooser1, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .add(6, 6, 6)
                .add(jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(jPanel1Layout.createSequentialGroup()
                        .add(5, 5, 5)
                        .add(jLabel88))
                    .add(txtUsername, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 20, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .add(6, 6, 6)
                .add(jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(jPanel1Layout.createSequentialGroup()
                        .add(5, 5, 5)
                        .add(jLabel1))
                    .add(jPasswordField1, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 20, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .add(6, 6, 6)
                .add(jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(jPanel1Layout.createSequentialGroup()
                        .add(5, 5, 5)
                        .add(jLabel2))
                    .add(jPasswordField2, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 20, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.UNRELATED)
                .add(jButton1)
                .addContainerGap(30, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel1, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    public void formload(String Userid){
        userSearch(Userid );
    }
    
    public boolean userSearch(String id ){
       boolean state=false;
       Session session = HibernateUtil.getSessionFactory().openSession();
       Transaction tx = null;
      try{
         tx = session.beginTransaction();
         DtUsers user = (DtUsers)session.get(DtUsers.class, id);
         if(user!=null){
              detail=user;
             setAdminFields();
             state=true;
         }else
//             clearAdminFields();
         tx.commit();
      }catch (HibernateException e) {
         if (tx!=null) tx.rollback();
         e.printStackTrace(); 
      }finally {
         session.close(); 
      }
      return state;
    }
    
    public void setAdminFields(){
        txtUfname.setText(detail.getFname());
        state=detail.getState();
//        txtUsname.setText(admin.getUserSname());
        txtUlname.setText(detail.getLname());
        txtUIdno.setText(detail.getIdNo());
        txtUphone.setText(detail.getPhone());
        txtUaddress.setText(detail.getAddress());
        jComboBox1.setSelectedItem(new superCls().getValue(detail.getGender()));
//        jComboBox2.setSelectedItem(new superCls().getValue(detail.getSpeciality()));
        jDateChooser1.setDate(new superCls().StringToDate(detail.getDob()));
        txtUResidence.setText(detail.getEmail());
//        txtUage.setText(admin.getUserAge());
        txtUsername.setText(detail.getUsername());
//        setUserChckBx(detail);
    }
    
    private void jPasswordField2FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jPasswordField2FocusLost
        // TODO add your handling code here:
        String password=new String(jPasswordField1.getPassword());
        String cpswd=new String(jPasswordField2.getPassword());
        if(!password.equals(cpswd)){
            JOptionPane.showMessageDialog(null,"Password dont match!","Clinic Management System",JOptionPane.WARNING_MESSAGE);
            jPasswordField1.setText("");
            jPasswordField2.setText("");
        }
}//GEN-LAST:event_jPasswordField2FocusLost

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        adminsetFields();
    }//GEN-LAST:event_jButton1ActionPerformed
  public void newUser(String state,String fname, String lname,String gender,String idno,String address,String phone,String email,String DOB,String Username,String speciality,String LF,String Pass,String date,String ul1,String ul2,String ul3,String ul4,String ul5,String ul6,String ul7,String ul8,String ul9){
     Session session = HibernateUtil.getSessionFactory().openSession();
     Transaction tx = null;
     try{
     tx = session.beginTransaction();
     DtUsers user = (DtUsers)session.get(DtUsers.class, idno);
     if(user==null){
     DtUsers user_save=new DtUsers(idno, state, fname, lname, gender, address, phone, email, DOB, Username, speciality, LF, Pass, date) ; 
     DtUserprivileges user_p=new DtUserprivileges(ul1, ul2, ul3, ul4, ul5, ul6, ul7, ul8, ul9,"","");
     user_save.setPrivileges(user_p);
     user_p.setUser(user_save);
     session.save(user_save);
     JLabel errorFields = new JLabel("<HTML><FONT COLOR = BLUE>New User added successfully</FONT></HTML>");
     JOptionPane.showMessageDialog(null,errorFields,"DMS",JOptionPane.INFORMATION_MESSAGE);
     }else{
         user.setAddress(address);
         user.setDate(date);
         user.setDob(DOB);
         user.setEmail(email);
         user.setFname(fname);
         user.setGender(gender);
         user.setIdNo(idno);
         user.setLname(lname);
         user.setLooknFeel(LF);
         user.setPassword(Pass);
         user.setPhone(phone);
         user.setSpeciality(speciality);
         user.setState(state);
         session.update(user);
         JLabel errorFields = new JLabel("<HTML><FONT COLOR = BLUE>User Record Updated successfully</FONT></HTML>");
         JOptionPane.showMessageDialog(null,errorFields,"DMS",JOptionPane.INFORMATION_MESSAGE);
     }
     tx.commit();
  }catch (HibernateException e) {
     if (tx!=null) tx.rollback();
       e.printStackTrace(); 
  }finally {
     session.close(); 
  }
}
   
  public void UserPrivileges(String idno,String ul1,String ul2,String ul3,String ul4,String ul5,String ul6,String ul7,String ul8,String ul9){
     Session session = HibernateUtil.getSessionFactory().openSession();
     Transaction tx = null;
     try{
     tx = session.beginTransaction();
     DtUserprivileges user_p=(DtUserprivileges)session.get(DtUserprivileges.class, idno);
     if(user_p==null){
         user_p=new DtUserprivileges(ul1, ul2, ul3, ul4, ul5, ul6, ul7, ul8, ul9,"","");
         session.save(user_p);        
     }else{
         user_p.setUl1(ul1);
         user_p.setUl2(ul2);
         user_p.setUl3(ul3);
         user_p.setUl4(ul4);
         user_p.setUl5(ul5);
         user_p.setUl6(ul6);
         user_p.setUl7(ul7);
         user_p.setUl8(ul8);
         user_p.setUl9(ul9);   
         session.update(user_p);
     }
     tx.commit();
  }catch (HibernateException e) {
     if (tx!=null) tx.rollback();
       e.printStackTrace(); 
  }finally {
     session.close(); 
  }
}
    
    
    
public void adminsetFields(){   
    String userFname,userLname,idNo,gender,adress,Tphone,email="",speciality="",dob,lf="aero",username,password,date,UL1,UL2,UL3,UL4,UL5;
    userFname=txtUfname.getText();
    userLname=txtUlname.getText();
    gender=jComboBox1.getSelectedItem().toString();
    idNo=txtUIdno.getText();
    adress=txtUaddress.getText();
    Tphone=txtUphone.getText();
    email=txtUResidence.getText();
    speciality=jComboBox2.getSelectedItem().toString();
    username=txtUsername.getText();
    dob=new SimpleDateFormat("dd-MM-yyyy").format(jDateChooser1.getDate());
    password=new String(jPasswordField1.getPassword());
    date=new SimpleDateFormat("dd-MM-yyyy").format(new Date());  
    if(!userFname.equals("")&& !idNo.equals("")&&!username.equals("")&& !password.equals("")){
        newUser(state,userFname, userLname, gender,idNo, adress,Tphone, email, dob, username,speciality,lf,password,date,"DENIED","DENIED","DENIED","DENIED","DENIED","DENIED","DENIED","DENIED","DENIED");
    }else{
          JLabel errorFields = new JLabel("<HTML><FONT COLOR = BLUE>Please Make sure Fname,Id,Password and usernames are filled</FONT></HTML>");	
          JOptionPane.showMessageDialog(null,errorFields,"Clinic management system",JOptionPane.WARNING_MESSAGE); 
    }

}
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JComboBox jComboBox1;
    private javax.swing.JComboBox jComboBox2;
    private com.toedter.calendar.JDateChooser jDateChooser1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel100;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel80;
    private javax.swing.JLabel jLabel82;
    private javax.swing.JLabel jLabel83;
    private javax.swing.JLabel jLabel84;
    private javax.swing.JLabel jLabel85;
    private javax.swing.JLabel jLabel86;
    private javax.swing.JLabel jLabel87;
    private javax.swing.JLabel jLabel88;
    private javax.swing.JLabel jLabel99;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPasswordField jPasswordField1;
    private javax.swing.JPasswordField jPasswordField2;
    private javax.swing.JTextField txtUIdno;
    private javax.swing.JTextField txtUResidence;
    private javax.swing.JTextField txtUaddress;
    private javax.swing.JTextField txtUfname;
    private javax.swing.JTextField txtUlname;
    private javax.swing.JTextField txtUphone;
    private javax.swing.JTextField txtUsername;
    // End of variables declaration//GEN-END:variables

}
